CREATE TABLE [cits].[stage_CITS_Input]
(
[ID] [int] NULL,
[Received by Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Last Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer First Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Phone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date Of Incident] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Time of Incident] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Direction of Travel] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location Street] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location Cross Street] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Route Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bus Number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Staff Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Call Back] [bit] NULL,
[Nature of Incident] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date of Staff Comments] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date Entered] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Given to Supervisor] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[record_updated_dt] [datetime2] NULL,
[record_updated_by] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOC] [bit] NOT NULL CONSTRAINT [DF__stage_CITS___NOC__1C5B4DE4] DEFAULT ((0)),
[Ridesource] [bit] NOT NULL CONSTRAINT [DF__stage_CIT__Rides__1D4F721D] DEFAULT ((0)),
[Employee Description] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Comments] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee Comments] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Staff Comments] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileSource] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
