CREATE TABLE [dbo].[dataedo_saved_info]
(
[report_id] [int] NOT NULL IDENTITY(1, 1),
[external_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[folder_external_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[title] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[url] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[embed_url] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[database_id] [int] NOT NULL,
[schema] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[object_type] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[definition] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dbms_creation_date] [datetime] NULL,
[dbms_last_modification_date] [datetime] NULL,
[synchronization_date] [datetime] NULL,
[synchronized_by] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creation_date] [datetime] NOT NULL,
[created_by] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_modification_date] [datetime] NOT NULL,
[modified_by] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[exists_in_DBMS] [bit] NULL,
[description_search] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field4] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field5] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field6] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field7] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field8] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field9] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field10] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field11] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field12] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field13] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field14] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field15] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field16] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field17] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field18] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field19] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field20] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field21] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field22] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field23] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field24] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field25] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field26] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field27] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field28] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field29] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field30] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field31] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field32] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field33] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field34] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field35] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field36] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field37] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field38] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field39] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field40] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description_plain] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_id] [int] NULL,
[source] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[subtype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[temp_sync_status] [bit] NOT NULL,
[update_id] [int] NULL,
[field41] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field42] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field43] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field44] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field45] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field46] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field47] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field48] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field49] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field50] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field51] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field52] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field53] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field54] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field55] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field56] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field57] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field58] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field59] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field60] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field61] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field62] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field63] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field64] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field65] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field66] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field67] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field68] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field69] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field70] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field71] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field72] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field73] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field74] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field75] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field76] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field77] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field78] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field79] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field80] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field81] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field82] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field83] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field84] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field85] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field86] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field87] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field88] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field89] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field90] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field91] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field92] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field93] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field94] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field95] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field96] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field97] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field98] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field99] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[field100] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[language] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[comments_count] [int] NOT NULL,
[rating] [decimal] (3, 2) NOT NULL,
[rating_count] [int] NOT NULL,
[open_warnings_count] [int] NOT NULL,
[warnings_count] [int] NOT NULL,
[open_todos_count] [int] NOT NULL,
[todos_count] [int] NOT NULL,
[parent_id] [int] NULL,
[parent_object_type] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description_source] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
