CREATE TABLE [dbo].[SubPwrData]
(
[Setup Table Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Memory Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Line Frequency] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Integration Period] [float] NULL,
[F5] [float] NULL,
[Logger Description Line] [float] NULL,
[F7] [float] NULL,
[Logger Serial Number] [float] NULL,
[F9] [float] NULL,
[Logger Type] [float] NULL,
[F11] [float] NULL,
[Firmware Version] [float] NULL,
[F13] [float] NULL,
[Peak Demand Minutes] [float] NULL,
[F15] [float] NULL,
[F16] [float] NULL,
[F17] [float] NULL,
[F18] [float] NULL,
[F19] [float] NULL,
[F20] [float] NULL,
[F21] [float] NULL,
[F22] [float] NULL,
[F23] [float] NULL,
[F24] [float] NULL,
[F25] [float] NULL,
[F26] [float] NULL,
[F27] [float] NULL,
[F28] [float] NULL,
[F29] [float] NULL,
[F30] [float] NULL,
[F31] [float] NULL,
[F32] [float] NULL,
[F33] [float] NULL,
[F34] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F35] [float] NULL,
[F36] [float] NULL,
[F37] [float] NULL,
[F38] [float] NULL,
[F39] [float] NULL,
[F40] [float] NULL,
[F41] [float] NULL,
[F42] [float] NULL,
[F43] [float] NULL,
[F44] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F45] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F46] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F47] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F48] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F49] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F50] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F51] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F52] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F53] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F54] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F55] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F56] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F57] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F58] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F59] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F60] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F61] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F62] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F63] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F64] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F65] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F66] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F67] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F68] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F69] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F70] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F71] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F72] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F73] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F74] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F75] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F76] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F77] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F78] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F79] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F80] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F81] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F82] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F83] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F84] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F85] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F86] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F87] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F88] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F89] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F90] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F91] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F92] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F93] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F94] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F95] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F96] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F97] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F98] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F99] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
GRANT SELECT ON  [dbo].[SubPwrData] TO [public]
GO
