CREATE TABLE [eam].[workOrderTaskCategoryTimeExtended_save]
(
[work_key] [int] NOT NULL IDENTITY(1, 1),
[calendar_id] [int] NOT NULL,
[work_order_yr] [int] NULL,
[work_order_no] [int] NULL,
[estimate] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[job_type] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comml_cost] [numeric] (12, 4) NULL,
[warranty] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account_id] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[indirect_flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[wcl_work_class] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[labor_cost_job] [numeric] (12, 4) NULL,
[labor_cost_lab] [numeric] (12, 4) NULL,
[work_order_status] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[datetime_out_service] [datetime] NULL,
[datetime_in_service] [datetime] NULL,
[datetime_closed] [datetime] NULL,
[datetime_unit_in] [datetime] NULL,
[qty_est_hours] [numeric] (12, 2) NULL,
[meter_1_life_total] [int] NULL,
[meter_1_reading] [int] NULL,
[TASK_task_code] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLASS_class_maint] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLASS_class_stds] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_entered] [datetime] NULL,
[lab_start_time] [datetime] NULL,
[lab_end_time] [datetime] NULL,
[task_type] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_reason] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_empl_no] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[labor_rate] [numeric] (12, 2) NULL,
[labor_hours] [numeric] (12, 2) NULL,
[jobmain_labor_hours] [numeric] (12, 2) NULL,
[labmain_labor_hours] [numeric] (12, 2) NULL,
[labor_date] [date] NULL,
[wo_task_inserted] [datetime] NULL,
[wo_task_calendar_id] [int] NULL,
[wo_task_yr_no] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_name] [varchar] (122) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_equip_no] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[life_miles] [int] NULL,
[ltd_bus_class] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bio_diesel] [int] NULL,
[atric] [int] NULL,
[emx_bus] [int] NULL,
[hybrid] [int] NULL,
[electric] [int] NULL,
[max_fuel] [int] NULL,
[active] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[unit_is_active] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ltd_bus_class_adj] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[repair_group] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[repair_group_code] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[repair_category] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[backupCategory] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_code] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[record_created_date] [datetime2] NULL CONSTRAINT [DF__workOrder__recor__333A20FC] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL,
[row_id] [int] NULL,
[group_row_id] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [eam].[workOrderTaskCategoryTimeExtended_save] ADD CONSTRAINT [PK_workOrderTaskCategoryTimeExtended_save] PRIMARY KEY CLUSTERED ([work_key]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_eam_workOrderTaskCategoryTimeExtended_save_70] ON [eam].[workOrderTaskCategoryTimeExtended_save] ([calendar_id]) ON [PRIMARY]
GO
