CREATE TABLE [eam].[qasset_status_history]
(
[eamAssetHistoryKey] [int] NOT NULL IDENTITY(1, 1),
[EquipmentID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EquipmentStatus] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LifeCycleStatusCodeID] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LifecycleStatusDescription] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusCategory] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryDescription] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DenotesThatUnitIsActive] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitAvailableForRepairOrPM] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MotorPoolDispatchStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DailyDepreciation] [numeric] (12, 2) NULL,
[DepreciationMethod] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LifeMonths] [int] NULL,
[MonthsRemaining] [int] NULL,
[ExcludeFromExceptionReports] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExcludeFromInventoryLists] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExcludeFromReplAnalysis] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastPerformedService] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextPMDueDate] [datetime] NULL,
[ElectricAsset] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlannedDeliveryDate] [datetime] NULL,
[ActualDeliveryDate] [datetime] NULL,
[PlannedInServiceDate] [datetime] NULL,
[ActualInServiceDate] [datetime] NULL,
[OriginalCost] [numeric] (12, 2) NULL,
[CapitalizedValue] [numeric] (12, 2) NULL,
[DateCapitalized] [datetime] NULL,
[LicenseNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__qasset_st__recor__72ADCC26] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
