CREATE TABLE [eam].[NTD_Equipment_Snapshot]
(
[eq_key_snapshot] [int] NOT NULL IDENTITY(1, 1),
[eq_equip_no] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLA_MAIN_Meter] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLA_MAIN_Maint] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLA_MAIN_PM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLA_MAIN_Rental] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLA_MAIN_Shop_Sch] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLA_MAIN_STDS] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPT_MAIN_department_name] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ECA_MAIN_category_Desc] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOC_MAIN_current] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOC_MAIN_Assigned_PM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOC_MAIN_Station] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOC_MAIN_Stored] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOC_MAIN_Repair] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_manufacturer] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_model] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRI_MAIN_priority_rank] [int] NULL,
[PRS_MAIN_unit_is_active] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_capital_exp_life_months] [int] NULL,
[eq_subsys_detail_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_RV_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Agency_Fleet_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Mod_TOS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Dedicated_Fleet] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Vehicle_Type_Svc] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Vehicle_Type] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Vehicle_Length] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Ownership] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_ADA_Accessible] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Funding_Source] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Year_of_Manufacture] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Year_of_rebuild] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Emerg_Contigency_veh] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Meter_1_usage] [int] NULL,
[eq_subsys_detail_Meter_2_usage] [int] NULL,
[eq_subsys_detail_Seating_Capacity] [int] NULL,
[eq_subsys_detail_Standing_Capacity] [int] NULL,
[eq_subsys_detail_Multi_Modal] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Fleet_name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Primary_Mode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Primary_Mode_Rev] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Primary_Service] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Estimated_Cost] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Transit_Agency_Cap_Resp] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Year_Dollars_of_Est_Cost] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Fuel_Type] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_subsys_detail_Dual_Fuel_Type] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subsys_subsystem] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CALENDAR_ID] [int] NOT NULL,
[CALENDAR_DATE] [date] NOT NULL,
[record_create_date] [datetime] NOT NULL CONSTRAINT [DF__NTD_Equip__recor__1DDCAF5E] DEFAULT (getdate()),
[ETLProcessActivityID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [eam].[NTD_Equipment_Snapshot] ADD CONSTRAINT [PK_NTD_Equipment_Snapshot] PRIMARY KEY NONCLUSTERED ([eq_key_snapshot]) ON [PRIMARY]
GO
