CREATE TABLE [eam].[HAMS_Non_Standard]
(
[FileName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column6] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column7] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column8] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column9] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column20] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column21] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column22] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column23] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column24] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column25] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column26] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column27] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column28] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column29] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column30] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column31] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column32] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
