CREATE TABLE [model].[Vehicle]
(
[ltd_veh_key] [int] NOT NULL IDENTITY(1, 1),
[ltd_bus_class] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EQ_equip_no] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VEHICLE TYPE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bus_text_class] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEHICLE YEAR] [int] NULL,
[UnitAgeDays] [int] NULL,
[VEHICLE MANUFACTURER] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEHICLE MODEL] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEHICLE DESC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[artic] [int] NOT NULL,
[emx_bus] [int] NOT NULL,
[hybrid] [int] NOT NULL,
[electric] [int] NOT NULL,
[SHOP STATUS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORK ORDER STATUS] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FUEL CARD NUMBER] [int] NULL,
[FIXED MONTHLY COST] [numeric] (12, 2) NULL,
[OPEN WORK ORDERS] [int] NULL,
[MONTHS IN OPERATION] [int] NULL,
[DEPRECIATION MONTHS LIFE] [int] NULL,
[DEPRECIATION MONTHS REMAINING] [int] NULL,
[LAST METER READING] [int] NULL,
[LIFE TOTAL MILES] [int] NULL,
[is_retired_or_sold] [int] NOT NULL,
[is_retired_or_sold_count] [int] NOT NULL,
[original_cost] [numeric] (12, 2) NULL,
[VEHICLE LENGTH FLEET] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[art_text] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[emx_text] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[hyb_text] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ele_text] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ltd_class_sort] [int] NULL,
[FLEET_TEXT] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROPERTY_TAG] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MFG_MODEL_TEXT] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEHICLE_TYPE_TEXT] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RNET_ADDRESS] [numeric] (5, 0) NULL,
[MODEL_YEAR] [numeric] (4, 0) NULL,
[DECOMMISSION] [bit] NOT NULL,
[TOTAL_CAPACITY] [numeric] (3, 0) NULL,
[FLEET_ID] [numeric] (5, 0) NULL,
[SEATING_CAPACITY] [numeric] (3, 0) NULL,
[VEHICLE_MFG_TEXT] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[license_no] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bus_kind] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__Vehicle_t__recor__6542BF51] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
ALTER TABLE [model].[Vehicle] ADD CONSTRAINT [pk_vehicle_key] PRIMARY KEY CLUSTERED ([ltd_veh_key], [EQ_equip_no]) ON [PRIMARY]
GO
