CREATE TABLE [ops].[dailyPiece]
(
[ops_dailyPiece_Key] [int] NOT NULL IDENTITY(1, 1),
[blockRoute] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[blockID] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[division] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[schDrivBegTime] [int] NOT NULL,
[opDate] [smalldatetime] NOT NULL,
[workClass] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[keyTime] [int] NOT NULL,
[schVehBegTime] [int] NOT NULL,
[emp_SID] [int] NULL,
[schdVehEndTime] [int] NOT NULL,
[actDriveEndPlace] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[actMiles] [int] NULL,
[actReliefBeg] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[schDrivEndTime] [int] NOT NULL,
[actReliefEnd] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[actVehBegTime] [int] NULL,
[actVehEndTime] [int] NULL,
[actDrivBegTime] [int] NULL,
[actDrivEndTime] [int] NULL,
[schVehBegPlace] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[actWorkTime] [int] NULL,
[schVehEndPlace] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[actVehBegPlace] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comments] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[actVehEndPlace] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cutPriority] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[payMethod] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dailyPieceFlags] [smallint] NOT NULL,
[baseRunNumber] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[boardID] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[runNumber] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vehicleType] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[appOrigin] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[pieceFlags] [smallint] NOT NULL,
[whoAssigned] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[whoPaid] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[schReliefBeg] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[schMiles] [int] NULL,
[schReliefEnd] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[runExceptions] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[schDrivBegPlace] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[schDrivEndPlace] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[actDrivBegPlace] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[schWorkTime] [int] NOT NULL,
[dayType] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[whoCreated] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[opDays] [smallint] NULL,
[workAccount] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[payReason] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[coverPaid] [int] NULL,
[vehicleID] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[callStatus] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[equipment] [smallint] NOT NULL,
[consist] [smallint] NULL,
[taxiIDStart] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[taxiIDEnd] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pieceRoute] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[breakReason] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[block_SID] [int] NULL,
[fareCardSequence] [int] NULL,
[notRunReason] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assignPhase] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[workBoard] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dailyPieceFlags2] [smallint] NOT NULL,
[actingEmp_SID] [int] NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__dailyPiec__recor__3F8920D0] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
ALTER TABLE [ops].[dailyPiece] ADD CONSTRAINT [PK_dailyPiece] PRIMARY KEY CLUSTERED ([ops_dailyPiece_Key]) ON [PRIMARY]
GO
