CREATE TABLE [pds].[Integration_ChargesHours]
(
[charge_hours_key] [bigint] NOT NULL IDENTITY(1, 1),
[context_user_id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ph_id] [int] NULL,
[phcntl_id] [int] NULL,
[person_id] [int] NULL,
[name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[first_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[middle_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[middle_initial] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[aka] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_id] [int] NULL,
[company_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[company] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[check_number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[check_date] [date] NULL,
[period_end_date] [date] NULL,
[charge_seq] [int] NULL,
[charge_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[charge_hours] [numeric] (12, 4) NULL,
[charge_amount] [numeric] (12, 4) NULL,
[charge_date] [date] NULL,
[charge_number] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[charge_position_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[charge_job_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[distribution_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[org_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[charge_shift_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[charge_shift_amount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[charge_rate] [numeric] (12, 4) NULL,
[charge_base_rate] [numeric] (12, 4) NULL,
[charge_percent] [numeric] (12, 4) NULL,
[shift_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_overtime] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__Integrati__recor__6644C3B6] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
