CREATE TABLE [tm].[BoardingStats]
(
[BoardingStatID] [int] NOT NULL IDENTITY(1, 1),
[calendar_id] [int] NULL,
[calendar_date] [datetime] NOT NULL,
[local_datetime] [datetime] NOT NULL,
[day_type] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bus_class] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[artic] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emx_bus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[the_bus] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mdt_time] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mdt_spm] [int] NULL,
[route] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[route_abbr] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[block] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dir] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tp_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tp_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stop_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stop_code] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stop_name] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[passenger_count_on] [int] NULL,
[passenger_count_off] [int] NULL,
[valid_odometer] [int] NOT NULL,
[valid_position] [int] NOT NULL,
[route_direction] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CalendarKey] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[maplat] [decimal] (38, 6) NULL,
[maplong] [decimal] (38, 6) NULL,
[LatLong] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[east_west_zone] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[north_south_zone] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[record_create_date] [datetime] NULL CONSTRAINT [DF__BoardingS__recor__5070F446] DEFAULT (sysdatetime()),
[record_update_date] [datetime] NULL
) ON [PRIMARY]
GO
