CREATE TABLE [tm].[DW_CALENDAR_SPM27]
(
[CAL_SPM_KEY] [bigint] NOT NULL,
[CALENDAR_ID] [numeric] (10, 0) NOT NULL,
[SPM] [int] NOT NULL,
[YYYYMMDD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Calendar Date Time] [datetime2] NOT NULL,
[CALENDAR_DATE] [date] NOT NULL
) ON [tm]
GO
ALTER TABLE [tm].[DW_CALENDAR_SPM27] ADD CONSTRAINT [PK_DW_CALENDAR_SPM27] PRIMARY KEY CLUSTERED ([CAL_SPM_KEY]) ON [tm]
GO
CREATE NONCLUSTERED INDEX [ix_DW_CALENDAR_SPM27_CalendarDateTime_CalendarID] ON [tm].[DW_CALENDAR_SPM27] ([Calendar Date Time], [CALENDAR_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [is_dw_calendar27_Calendar_ID] ON [tm].[DW_CALENDAR_SPM27] ([CALENDAR_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [is_dw_calendar27_Calendar_ID_Includes1] ON [tm].[DW_CALENDAR_SPM27] ([CALENDAR_ID]) INCLUDE ([SPM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [is_dw_calendar27_Calendar_ID_Includes4] ON [tm].[DW_CALENDAR_SPM27] ([CALENDAR_ID]) INCLUDE ([SPM], [YYYYMMDD], [Calendar Date Time], [CALENDAR_DATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [is_dw_calendar27_Calendar_ID_Includes2] ON [tm].[DW_CALENDAR_SPM27] ([CALENDAR_ID], [SPM]) INCLUDE ([YYYYMMDD], [Calendar Date Time], [CALENDAR_DATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_DW_CALENDAR_SPM27_SPM] ON [tm].[DW_CALENDAR_SPM27] ([SPM]) INCLUDE ([CALENDAR_DATE]) ON [PRIMARY]
GO
