CREATE TABLE [tm].[EXCEPTION]
(
[EXCEPTION_KEY] [int] NOT NULL IDENTITY(1, 1),
[EXC_ID] [int] NOT NULL,
[EXC_NAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXC_ABBR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DAY_FLAGS] [int] NULL,
[EXCLUSION_NUMBER] [int] NULL,
[AGENCY_ID] [int] NOT NULL CONSTRAINT [DF__EXCEPTION__AGENC__752C0E96] DEFAULT ((0)),
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__EXCEPTION__recor__7437EA5D] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
ALTER TABLE [tm].[EXCEPTION] ADD CONSTRAINT [PK_EXCEPTION] PRIMARY KEY CLUSTERED ([EXCEPTION_KEY]) ON [PRIMARY]
GO
