CREATE TABLE [tm].[EXCEPTION_COMBO_XREF]
(
[EXCEPTION_COMBO_XREF_KEY] [int] NOT NULL IDENTITY(1, 1),
[EXC_COMBO_ID] [int] NOT NULL,
[EXC_ID] [int] NOT NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__EXCEPTION__recor__78FC9F7A] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
ALTER TABLE [tm].[EXCEPTION_COMBO_XREF] ADD CONSTRAINT [PK_EXCEPTION_COMBO_XREF] PRIMARY KEY CLUSTERED ([EXCEPTION_COMBO_XREF_KEY]) ON [PRIMARY]
GO
