CREATE TABLE [tm].[VIEW_STORE_ADH_Archive]
(
[calendar_id] [numeric] (10, 0) NOT NULL,
[calendar_date] [datetime] NOT NULL,
[day_type] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ttv_id] [numeric] (5, 0) NOT NULL,
[ttv] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[bid] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[block_id] [numeric] (10, 0) NULL,
[block] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[block_numeric] [int] NULL,
[emx_block] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[taxi_block] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trip_start] [numeric] (10, 0) NULL,
[trip_end] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_end_time] [int] NULL,
[sched] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sched_sql] [int] NULL,
[sched_spm] [numeric] (10, 0) NOT NULL,
[actual_arrival_spm] [int] NULL,
[actual_departure_spm] [int] NULL,
[arrive] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[arrive_sql] [int] NULL,
[depart] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[depart_sql] [int] NULL,
[adhere_sec] [numeric] (11, 0) NULL,
[adhere_min] [numeric] (9, 2) NULL,
[dwell_sec] [int] NULL,
[dwell_min] [numeric] (9, 2) NULL,
[adherence] [numeric] (5, 0) NULL,
[arrival_adhere_mins] [numeric] (6, 2) NULL,
[end_of_trip] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trip_end_important_tp] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trip_end_missed] [int] NULL,
[trip_end_ontime] [int] NULL,
[trip_end_late_0_2] [int] NULL,
[trip_end_late_2_4] [int] NULL,
[trip_end_late_4_6] [int] NULL,
[trip_end_late_6_plus] [int] NULL,
[sched_interval] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[actual_interval] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[actual_dwell] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[actual_int_plus_dwell] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_id] [numeric] (10, 0) NULL,
[revenue_id] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[route] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dir] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[rte_public] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rte_and_dir] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rte_rural] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rev_rte] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[pattern] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[the_bus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[odometer] [numeric] (9, 2) NULL,
[sched_miles_since_last] [numeric] (9, 2) NULL,
[bus_class] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[artic] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emx_bus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[service_type] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[service_type_general] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[svc] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[run] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[block_stop_order] [int] NOT NULL,
[pattern_geo_node_seq] [numeric] (7, 0) NULL,
[stop] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[stop_name] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tp] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tp_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sa_tp] [int] NOT NULL,
[trip_start_stop] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_start_stop_name] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_end_stop] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_end_stop_name] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operator_id] [numeric] (5, 0) NULL,
[badge] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operator_first] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operator_last] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operator] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operators_supervisor] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operator_jobcode] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_layover] [bit] NULL,
[white_line] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[drop_off_only] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ltd_status] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[waiver_id] [numeric] (9, 0) NULL,
[waiver_description] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[waivers_in_one] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[waiver_late_ok] [numeric] (1, 0) NULL,
[waiver_early_ok] [numeric] (1, 0) NULL,
[waiver_missed_ok] [numeric] (1, 0) NULL,
[late_waived_tp] [numeric] (5, 0) NULL,
[early_waived_tp] [numeric] (5, 0) NULL,
[missing_waived_tp] [numeric] (5, 0) NULL,
[late_count] [numeric] (7, 0) NULL,
[early_count] [numeric] (7, 0) NULL,
[ontime_count] [numeric] (7, 0) NULL,
[missing_count] [numeric] (7, 0) NULL,
[adjusted_late] [numeric] (5, 0) NULL,
[adjusted_early] [numeric] (5, 0) NULL,
[adjusted_ontime] [numeric] (5, 0) NULL,
[adjusted_missing] [numeric] (5, 0) NULL,
[layover_late_allowed] [numeric] (5, 0) NULL,
[layover_early_allowed] [numeric] (5, 0) NULL,
[spm_planner] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[bsi] [tinyint] NULL,
[overload_id] [int] NULL,
[adherence_id] [int] NOT NULL,
[fom] [int] NULL,
[valid_odometer] [int] NOT NULL,
[valid_adherence] [int] NOT NULL,
[valid_position] [int] NOT NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__VIEW_STOR__recor__7A403A0D] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [tm].[VIEW_STORE_ADH_Archive] ADD CONSTRAINT [PK_VIEW_STORE_ADH_Archive] PRIMARY KEY CLUSTERED ([adherence_id]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_VIEW_STORE_ADH_Archive_calendar_date_includes] ON [tm].[VIEW_STORE_ADH_Archive] ([calendar_date]) INCLUDE ([day_type], [ttv_id], [ttv], [bid], [block_id], [block], [block_numeric], [emx_block], [taxi_block], [trip_start], [trip_end], [trip_end_time], [sched], [sched_sql], [actual_arrival_spm], [actual_departure_spm], [arrive], [arrive_sql], [depart], [depart_sql], [adhere_sec], [adhere_min], [dwell_sec], [dwell_min], [adherence], [arrival_adhere_mins], [end_of_trip], [trip_end_important_tp], [trip_end_missed], [trip_end_ontime], [trip_end_late_0_2], [trip_end_late_2_4], [trip_end_late_4_6], [trip_end_late_6_plus], [sched_interval], [actual_interval], [actual_dwell], [actual_int_plus_dwell], [trip_id], [revenue_id], [rte_public], [rte_and_dir], [rte_rural], [rev_rte], [pattern], [odometer], [sched_miles_since_last], [bus_class], [artic], [emx_bus], [service_type], [service_type_general], [svc], [run], [block_stop_order], [pattern_geo_node_seq], [stop], [stop_name], [tp], [tp_name], [sa_tp], [trip_start_stop], [trip_start_stop_name], [trip_end_stop], [trip_end_stop_name], [operator_id], [badge], [operator_first], [operator_last], [operator], [operators_supervisor], [operator_jobcode], [is_layover], [white_line], [drop_off_only], [ltd_status], [waiver_id], [waiver_description], [waivers_in_one], [waiver_late_ok], [waiver_early_ok], [waiver_missed_ok], [late_waived_tp], [early_waived_tp], [missing_waived_tp], [late_count], [early_count], [ontime_count], [missing_count], [adjusted_late], [adjusted_early], [adjusted_ontime], [adjusted_missing], [layover_late_allowed], [layover_early_allowed], [spm_planner], [bsi], [overload_id], [fom], [valid_odometer], [valid_adherence], [valid_position], [record_created_date]) ON [PRIMARY]
GO
