CREATE TABLE [tm].[VEHICLE_INSPECTION_DATA]
(
[dwVIDId] [int] NOT NULL IDENTITY(1, 1),
[VEHICLE_INSPECTION_DATA_ID] [int] NOT NULL,
[CALENDAR_ID] [numeric] (10, 0) NOT NULL,
[SOURCE_HOST] [smallint] NOT NULL,
[LATITUDE] [int] NOT NULL,
[LONGITUDE] [int] NOT NULL,
[ODOMETER] [int] NOT NULL,
[CURRENT_DRIVER] [int] NOT NULL,
[FAILURES] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMMENTS] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INSPECTION_IMAGE] [varbinary] (max) NULL,
[STATUS] [numeric] (1, 0) NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__VEHICLE_I__recor__5C9E8F76] DEFAULT (sysdatetime())
) ON [PRIMARY]
GO
ALTER TABLE [tm].[VEHICLE_INSPECTION_DATA] ADD CONSTRAINT [XPKVEHICLE_INSPECTION_DATA] PRIMARY KEY CLUSTERED ([CALENDAR_ID], [SOURCE_HOST], [LATITUDE], [LONGITUDE], [ODOMETER], [CURRENT_DRIVER]) ON [PRIMARY]
GO
