CREATE TABLE [tm].[VIEW_STORE_ADH]
(
[calendar_id] [numeric] (10, 0) NOT NULL,
[calendar_date] [datetime] NOT NULL,
[day_type] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ttv_id] [numeric] (5, 0) NOT NULL,
[ttv] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[bid] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[block_id] [numeric] (10, 0) NULL,
[block] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[block_numeric] [int] NULL,
[emx_block] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[taxi_block] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trip_start] [numeric] (10, 0) NULL,
[trip_end] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_end_time] [int] NULL,
[sched] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sched_sql] [int] NULL,
[sched_spm] [numeric] (10, 0) NOT NULL,
[actual_arrival_spm] [int] NULL,
[actual_departure_spm] [int] NULL,
[arrive] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[arrive_sql] [int] NULL,
[depart] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[depart_sql] [int] NULL,
[adhere_sec] [numeric] (11, 0) NULL,
[adhere_min] [numeric] (9, 2) NULL,
[dwell_sec] [int] NULL,
[dwell_min] [numeric] (9, 2) NULL,
[adherence] [numeric] (5, 0) NULL,
[arrival_adhere_mins] [numeric] (6, 2) NULL,
[end_of_trip] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trip_end_important_tp] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trip_end_missed] [int] NULL,
[trip_end_ontime] [int] NULL,
[trip_end_late_0_2] [int] NULL,
[trip_end_late_2_4] [int] NULL,
[trip_end_late_4_6] [int] NULL,
[trip_end_late_6_plus] [int] NULL,
[sched_interval] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[actual_interval] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[actual_dwell] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[actual_int_plus_dwell] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_id] [numeric] (10, 0) NULL,
[revenue_id] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[route] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dir] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[rte_public] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rte_and_dir] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rte_rural] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rev_rte] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[pattern] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[the_bus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[odometer] [numeric] (9, 2) NULL,
[sched_miles_since_last] [numeric] (9, 2) NULL,
[bus_class] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[artic] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emx_bus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[service_type] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[service_type_general] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[svc] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[run] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[block_stop_order] [int] NOT NULL,
[pattern_geo_node_seq] [numeric] (7, 0) NULL,
[stop] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[stop_name] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tp] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tp_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sa_tp] [int] NOT NULL,
[trip_start_stop] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_start_stop_name] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_end_stop] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_end_stop_name] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operator_id] [numeric] (5, 0) NULL,
[badge] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operator_first] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operator_last] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operator] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operators_supervisor] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operator_jobcode] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_layover] [bit] NULL,
[white_line] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[drop_off_only] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ltd_status] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[waiver_id] [numeric] (9, 0) NULL,
[waiver_description] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[waivers_in_one] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[waiver_late_ok] [numeric] (1, 0) NULL,
[waiver_early_ok] [numeric] (1, 0) NULL,
[waiver_missed_ok] [numeric] (1, 0) NULL,
[late_waived_tp] [numeric] (5, 0) NULL,
[early_waived_tp] [numeric] (5, 0) NULL,
[missing_waived_tp] [numeric] (5, 0) NULL,
[late_count] [numeric] (7, 0) NULL,
[early_count] [numeric] (7, 0) NULL,
[ontime_count] [numeric] (7, 0) NULL,
[missing_count] [numeric] (7, 0) NULL,
[adjusted_late] [numeric] (5, 0) NULL,
[adjusted_early] [numeric] (5, 0) NULL,
[adjusted_ontime] [numeric] (5, 0) NULL,
[adjusted_missing] [numeric] (5, 0) NULL,
[layover_late_allowed] [numeric] (5, 0) NULL,
[layover_early_allowed] [numeric] (5, 0) NULL,
[spm_planner] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[bsi] [tinyint] NULL,
[overload_id] [int] NULL,
[adherence_id] [int] NOT NULL,
[fom] [int] NULL,
[valid_odometer] [int] NOT NULL,
[valid_adherence] [int] NOT NULL,
[valid_position] [int] NOT NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__VIEW_STOR__recor__29EF4D2F] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [tm].[VIEW_STORE_ADH] ADD CONSTRAINT [PK_VIEW_STORE_ADH] PRIMARY KEY CLUSTERED ([adherence_id]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_tm_VIEW_STORE_ADH_23077] ON [tm].[VIEW_STORE_ADH] ([block], [calendar_date]) INCLUDE ([emx_block]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_VIEW_STORE_ADH_calendar_date] ON [tm].[VIEW_STORE_ADH] ([calendar_date]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_tm_VIEW_STORE_ADH_calendar_date_includes3] ON [tm].[VIEW_STORE_ADH] ([calendar_date]) INCLUDE ([adhere_min], [stop], [stop_name]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_tm_VIEW_STORE_ADH_23072] ON [tm].[VIEW_STORE_ADH] ([calendar_date]) INCLUDE ([block]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_view_store_adh_calendar_id_the_bus] ON [tm].[VIEW_STORE_ADH] ([calendar_id], [the_bus]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_VIEW_STORE_ADH_revenue_id_bus_calendar_id] ON [tm].[VIEW_STORE_ADH] ([revenue_id], [the_bus], [calendar_id]) ON [PRIMARY]
GO
