CREATE TABLE [wrk].[workOrderDW]
(
[X_datetime_insert] [datetime] NULL,
[work_order_yr] [int] NULL,
[work_order_no] [int] NULL,
[estimate] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[job_type] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[wcl_work_class] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_equip_no_jobm9921ain] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_order_status] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[datetime_out_service] [datetime] NULL,
[datetime_in_service] [datetime] NULL,
[datetime_closed] [datetime] NULL,
[datetime_unit_in] [datetime] NULL,
[qty_est_hours] [numeric] (12, 1) NULL,
[meter_1_life_total] [int] NULL,
[meter_1_reading] [int] NULL,
[TASK_task_code] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_type] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_reason] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_empl_no] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[labor_rate] [numeric] (12, 2) NULL,
[labor_hours] [numeric] (12, 1) NULL,
[lab_date] [datetime] NULL,
[wo_task_inserted] [datetime] NULL,
[wo_task_calendar_id] [int] NULL,
[wo_task_yr_no] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_name] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_equip_no] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[life_miles] [int] NULL,
[ltd_bus_class] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[bio_diesel] [int] NOT NULL,
[atric] [int] NOT NULL,
[emx_bus] [int] NOT NULL,
[hybrid] [int] NOT NULL,
[electric] [int] NOT NULL,
[max_fuel] [int] NOT NULL,
[active] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[unit_is_active] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ltd_bus_class_adj] [int] NULL,
[repair_group] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[repair_group_code] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[repair_category] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[backupCategory] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
