CREATE TABLE [wrk].[DWELL_RESEARCH]
(
[DWELL_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[SOURCE_ID] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CALENDAR_ID] [bigint] NOT NULL,
[TIME_TABLE_VERSION_NAME] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ROUTE_DIRECTION_ABBR] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROUTE_ABBR] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STOP_ABBR] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STOP_NAME] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BLOCK_ABBR] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEHICLE_ID] [int] NULL,
[TRIP_ID] [bigint] NULL,
[TRIP_END_TIME] [int] NULL,
[SERVICE_ABBR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REVENUE_ID] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IS_LAYOVER] [bit] NULL,
[MESSAGE_TIME] [int] NULL,
[SCHEDULED_TIME] [int] NULL,
[ACTUAL_ARRIVAL_TIME] [int] NULL,
[ACTUAL_DEPARTURE_TIME] [int] NULL,
[IS_DOOR_OPENED] [bit] NULL,
[FIRST_DOOR_OPEN_TIME] [int] NULL,
[LAST_DOOR_CLOSE_TIME] [int] NULL,
[BOARD] [int] NULL,
[ALIGHT] [int] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_DWELL_RESEARCH_Calendar_ID] ON [wrk].[DWELL_RESEARCH] ([CALENDAR_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_DWELL_RESEARCH_REVENUE_ID_IS_LAYOVER_INCLUDES] ON [wrk].[DWELL_RESEARCH] ([REVENUE_ID], [IS_LAYOVER]) INCLUDE ([CALENDAR_ID], [TIME_TABLE_VERSION_NAME], [ROUTE_DIRECTION_ABBR], [ROUTE_ABBR], [STOP_ABBR], [STOP_NAME], [TRIP_ID], [TRIP_END_TIME], [SERVICE_ABBR], [SCHEDULED_TIME], [ACTUAL_ARRIVAL_TIME], [ACTUAL_DEPARTURE_TIME], [FIRST_DOOR_OPEN_TIME], [LAST_DOOR_CLOSE_TIME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_DWELL_RESEARCH_REVENUE_ISLAYOBER_CALID_INCLUDES] ON [wrk].[DWELL_RESEARCH] ([REVENUE_ID], [IS_LAYOVER], [CALENDAR_ID]) INCLUDE ([TIME_TABLE_VERSION_NAME], [ROUTE_DIRECTION_ABBR], [ROUTE_ABBR], [STOP_ABBR], [STOP_NAME], [TRIP_ID], [TRIP_END_TIME], [SERVICE_ABBR], [SCHEDULED_TIME], [ACTUAL_ARRIVAL_TIME], [ACTUAL_DEPARTURE_TIME], [FIRST_DOOR_OPEN_TIME], [LAST_DOOR_CLOSE_TIME]) ON [PRIMARY]
GO
