CREATE TABLE [cits].[archive_CITS_Input]
(
[cits_archive_key] [bigint] NOT NULL IDENTITY(1, 1),
[ID] [int] NULL,
[Received by Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Last Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer First Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Phone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date Of Incident] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Time of Incident] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Direction of Travel] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location Street] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location Cross Street] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Route Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bus Number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee Number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Staff Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Call Back] [bit] NULL,
[Nature of Incident] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date of Staff Comments] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date Entered] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Given to Supervisor] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[record_updated_dt] [datetime2] NULL,
[record_updated_by] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOC] [bit] NOT NULL CONSTRAINT [DF__archive_CIT__NOC__6BB81689] DEFAULT ((0)),
[Ridesource] [bit] NOT NULL CONSTRAINT [DF__archive_C__Rides__6CAC3AC2] DEFAULT ((0)),
[FileSource] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee Description] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Comments] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee Comments] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Staff Comments] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[record_created_date] [datetime2] NULL CONSTRAINT [DF__archive_C__recor__6DA05EFB] DEFAULT (sysdatetime())
) ON [PRIMARY]
GO
