CREATE TABLE [dbo].[sizetable]
(
[rn] [bigint] NULL,
[work_order_yr] [int] NULL,
[work_order_no] [int] NULL,
[work_order_yr_no] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_order_yr_no_tsk] [varchar] (98) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[TASK_task_code] [varchar] (12) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[account_id] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[usr_closed_by] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usr_finished_by] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EQ_equip_no] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[meter_1_reading] [int] NULL,
[meter_1_life_total] [int] NULL,
[EMP_empl_no] [varchar] (9) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[unique_id] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[lab_date] [datetime] NULL,
[lab_date_int] [int] NULL,
[date_entered] [datetime] NULL,
[CLASS_class_stds] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[CLASS_class_maint] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[labor_rate] [numeric] (12, 2) NULL,
[lab_start_datetime] [datetime] NULL,
[lab_end_datetime] [datetime] NULL,
[hours_span_in_lab] [numeric] (17, 6) NULL,
[indirect_flag] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[labor_hours] [numeric] (12, 1) NULL,
[eam_labor_cost] [numeric] (12, 2) NULL,
[ltd_calculated_labor_cost] [numeric] (25, 3) NULL,
[parts_issued_value] [numeric] (38, 6) NULL,
[reason_for_repair] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rsn_category] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_status] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[MilesAtLastRC] [int] NULL,
[milesBetweenRC] [int] NULL,
[rtcc_task] [varchar] (12) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[repair_group_code] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[repair_group] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_type] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_type_description] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
