CREATE TABLE [dim].[z TTV_PATTERN_RTE_DIR_STOP]
(
[TTV_ROUTE_DIR_STOP_KEY] [int] NOT NULL IDENTITY(1, 1),
[TIME_TABLE_VERSION_ID] [numeric] (5, 0) NOT NULL,
[ROUTE_ID] [int] NOT NULL,
[ROUTE_DIRECTION_ID] [numeric] (5, 0) NOT NULL,
[GEO_NODE_ID] [numeric] (10, 0) NOT NULL,
[ROUTE_ABBR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ROUTE_NAME] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STOP_ABBR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STOP_NAME] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPARTURE_ZONE] [smallint] NULL,
[ARRIVAL_ZONE] [smallint] NULL,
[GEO_NODE_ABBR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GEO_NODE_NAME] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LATITUDE] [numeric] (21, 9) NULL,
[LONGITUDE] [numeric] (21, 9) NULL,
[RTE_DIR_STOP_KEY] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TTV_RTE_DIR_STOP_KEY] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__TTV_ROUTE__recor__179240AF] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dim].[z TTV_PATTERN_RTE_DIR_STOP] ADD CONSTRAINT [PK_TTV_ROUTE_DIR_STOP] PRIMARY KEY CLUSTERED ([TIME_TABLE_VERSION_ID], [ROUTE_ID], [ROUTE_DIRECTION_ID], [GEO_NODE_ID]) ON [PRIMARY]
GO
