CREATE TABLE [eam].[work_order_detail_stage]
(
[calendar_id] [int] NULL,
[work_order_yr] [int] NOT NULL,
[work_order_no] [int] NOT NULL,
[estimate] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[job_type] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_equip_no] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_order_status] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[datetime_out_service] [datetime] NULL,
[datetime_in_service] [datetime] NULL,
[datetime_closed] [datetime] NULL,
[datetime_unit_in] [datetime] NULL,
[qty_est_hours] [numeric] (13, 2) NULL,
[meter_1_life_total] [int] NULL,
[meter_1_reading] [int] NULL,
[wcl_work_class] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_entered] [datetime] NULL,
[labor_date] [date] NULL,
[lab_date] [smalldatetime] NULL,
[TASK_task_code] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REAS_reas_for_repair] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLASS_class_maint] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLASS_class_stds] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lab_start_time] [datetime] NULL,
[lab_end_time] [datetime] NULL,
[task_type] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_reason] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_empl_no] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[labor_rate] [numeric] (12, 2) NULL,
[labor_cost_job] [numeric] (12, 2) NULL,
[labor_cost_lab] [numeric] (12, 2) NULL,
[calc_cost] [numeric] (38, 4) NULL,
[jobmain_labor_hours] [numeric] (13, 2) NULL,
[labmain_labor_hours] [numeric] (38, 2) NULL,
[comml_cost] [numeric] (12, 2) NULL,
[warranty] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[indirect_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[time_time_code] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[row_id] [int] NULL,
[group_row_id] [int] NULL,
[wo_task_inserted] [datetime] NULL,
[wo_task_calendar_id] [int] NULL,
[wo_task_yr_no] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_name] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[life_miles] [int] NULL,
[ltd_bus_class] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bio_diesel] [int] NULL,
[atric] [int] NULL,
[emx_bus] [int] NULL,
[hybrid] [int] NULL,
[electric] [int] NULL,
[max_fuel] [int] NULL,
[active] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[unit_is_active] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ltd_bus_class_adj] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[repair_group_code] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[backupCategory] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[repair_category] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[repair_group] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[breakdown_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rsn_category] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[repair_category_check] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_road_call] [bit] NOT NULL CONSTRAINT [DF__work_orde__is_ro__0514FA47] DEFAULT ((0)),
[MilesAtLastRC] [int] NULL,
[milesBetweenRC] [int] NULL,
[job_account_id] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[labor_account_id] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_warranty] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_warranty_short] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
