CREATE TABLE [eam].[equipment_main_addl]
(
[eq_key_addl] [int] NOT NULL IDENTITY(1, 1),
[X_datetime_insert] [datetime] NULL,
[X_userid_insert] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DB_ACC] [smallint] NULL,
[row_id] [int] NOT NULL,
[EQ_equip_no] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PART_part_no] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[part_suffix] [int] NULL,
[position] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mark_marker_from] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mark_marker_to] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seg_segment_from] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seg_segment_to] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elevation_from] [decimal] (12, 4) NULL,
[elevation_to] [decimal] (12, 4) NULL,
[latitude_from] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[latitude_to] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[longitude_from] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[longitude_to] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[repl_model_excl_switch] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[email_pm_sent] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOC_last_order_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_order_yr] [int] NULL,
[LAST_order_no] [int] NULL,
[TASK_last_pm_service] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOC_stock_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comp_meter_upd] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sale_price_net] [numeric] (12, 2) NULL,
[sale_expenses] [numeric] (12, 2) NULL,
[sale_commission] [numeric] (12, 2) NULL,
[last_unique_id] [int] NULL,
[lease_expiration_meter] [int] NULL,
[last_pm_date_source] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_source] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[position_link] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINE_line_id] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COND_condition_id] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_offset_from] [decimal] (12, 4) NULL,
[total_offset_to] [decimal] (12, 4) NULL,
[ACCT_cml_acct_code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCT_ftk_acct_code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCT_lab_acct_code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCT_pts_acct_code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCT_usg_acct_code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REGCLASS_id] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTY_id] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[registration_value] [decimal] (12, 2) NULL,
[postal_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VRG_valuecode_id] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WAPROF_assign_profile_id] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[license_issue_date] [datetime] NULL,
[purchase_year] [int] NULL,
[COUNTY_secondary_id] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEG_boundary_segment] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COND_auto_condition_id] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_cond_date] [datetime] NULL,
[last_autocond_date] [datetime] NULL,
[last_cond_source] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_autocond_source] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USR_cond_lastuser] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USR_autocond_lastuser] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_offset_from] [decimal] (12, 4) NULL,
[x_offset_to] [decimal] (12, 4) NULL,
[y_offset_from] [decimal] (12, 4) NULL,
[y_offset_to] [decimal] (12, 4) NULL,
[z_offset_from] [decimal] (12, 4) NULL,
[z_offset_to] [decimal] (12, 4) NULL,
[SHAPE_id] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILLTYP_billingtype_id] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMG_class_id] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADR_address_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description_style1] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description_style2] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description_style3] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description_style4] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[show_in_work_mgmt] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_datetime_update] [datetime] NULL,
[ADR_transferee_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_full_charge_meter] [int] NULL,
[last_full_charge_date] [datetime] NULL,
[electric_asset] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACM_run_id] [int] NULL,
[ACM_model_unique_id] [int] NULL,
[ACM_component_id] [int] NULL,
[ACM_is_compliant] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACM_require_for_service_error] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACM_datetime_run] [datetime] NULL,
[DEPLOYMENT_STATUS_id] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[event_id] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[device_id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loan_amount] [decimal] (12, 2) NULL,
[loan_duration_months] [int] NULL,
[loan_annual_interest_rate] [decimal] (12, 3) NULL,
[loan_start_date] [datetime] NULL,
[VEND_last_pm_vendor_no] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_pm_cml_unique_id] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[daily_depreciation_rate] [decimal] (12, 2) NULL,
[ETLProcessActivityID] [int] NOT NULL,
[record_create_date] [datetime] NULL CONSTRAINT [DF__equipment__recor__67809EAD] DEFAULT (getdate()),
[begin_date] [date] NOT NULL,
[end_date] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [eam].[equipment_main_addl] ADD CONSTRAINT [PK_equipment_main_addl] PRIMARY KEY NONCLUSTERED ([eq_key_addl]) ON [PRIMARY]
GO
