CREATE TABLE [eam].[equipment_main]
(
[eq_key] [int] NOT NULL IDENTITY(1, 1),
[eq_equip_no] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROCST_proc_status] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EQCAT_equip_category] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOC_assign_pm_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOC_assign_repr_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOC_stored_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_dept_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CPY_company_code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLASS_class_maint] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLASS_class_meter] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLASS_class_pm] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLASS_class_shop_sch] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLASS_class_rental] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLASS_class_stds] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[license_no] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[asset_no] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pm_prog_type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FLT_fleet_no] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACAT_category_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[asset_type] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[equipment_status_date] [datetime] NOT NULL,
[X_datetime_update] [datetime] NULL,
[X_datetime_insert] [datetime] NULL,
[record_created_date] [datetime] NOT NULL CONSTRAINT [DF__equipment__recor__45D4C6C8] DEFAULT (getdate()),
[record_updated_date] [datetime] NULL,
[ETLProcessActivityID] [int] NOT NULL,
[begin_date] [date] NULL,
[end_date] [date] NULL,
[EQTYP_equip_type] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[year] [int] NULL,
[manufacturer] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[model] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sla_status] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_order_status] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fuel_card_no] [int] NULL,
[months_in_operation] [int] NULL,
[deprec_months_life] [int] NULL,
[depr_mths_remaining] [int] NULL,
[shop_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[scap] [int] NULL,
[LOC_assgn_mobile_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comment_area] [varchar] (1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_temp_loaned_to] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[on_temp_loan] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[in_service_date] [datetime] NULL,
[inv_list_excl_switch] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_meter_1_reading] [int] NULL,
[last_meter_2_reading] [int] NULL,
[LOC_station_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOC_current_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[meter_1_type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[meter_2_type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[original_cost] [decimal] (12, 2) NULL,
[PRI_shop_priority] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[serial_no] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status_codes] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[life_total_meter_2] [int] NULL,
[own_lease_customer] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oper_name] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCT_acct_code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[est_replace_cost] [decimal] (12, 2) NULL,
[est_replace_yr] [int] NULL,
[est_replace_mo] [int] NULL,
[replace_code] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[delivery_date] [datetime] NULL,
[meter_1_at_delivery] [int] NULL,
[meter_2_at_delivery] [int] NULL,
[monthly_rent] [decimal] (12, 2) NULL,
[retire_date] [datetime] NULL,
[sale_date] [datetime] NULL,
[sale_price] [decimal] (14, 2) NULL,
[disposal_method] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_pm_sched_date] [datetime] NULL,
[next_pm_sched_date] [datetime] NULL,
[inspection_month] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stat_inspect_month] [int] NULL,
[stat_inspect_year] [int] NULL,
[stat_inspect_interv] [int] NULL,
[last_pm_slot] [int] NULL,
[next_pm_slot] [int] NULL,
[pm_meter_1_interval] [int] NULL,
[pm_meter_2_interval] [int] NULL,
[pm_fuel_override] [int] NULL,
[pm_pref_shift] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oil_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[depreciation_method] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[depr_cur_decline_bal] [decimal] (12, 2) NULL,
[salvage_value] [int] NULL,
[cost_rpt_excl_switch] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[excp_rpt_excl_switch] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_pm_notify_dept] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_orders_ok] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fuel_tickets_ok] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usage_tickets_ok] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[disposal_reason] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[planned_deliv_date] [datetime] NULL,
[planned_insvc_date] [datetime] NULL,
[planned_retir_date] [datetime] NULL,
[disposal_authority] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[est_meter_at_replace] [int] NULL,
[last_meter_source] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fixed_monthly_cost] [decimal] (12, 2) NULL,
[fixed_replace_cost] [decimal] (12, 2) NULL,
[fixed_licensing_cost] [decimal] (12, 2) NULL,
[fixed_cost_other_1] [decimal] (12, 2) NULL,
[fixed_cost_other_2] [decimal] (12, 2) NULL,
[fixed_cost_other_3] [decimal] (12, 2) NULL,
[fixed_insurance_cost] [decimal] (12, 2) NULL,
[orig_regist_date] [datetime] NULL,
[license_st] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[regist_expire_date] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [eam].[equipment_main] ADD CONSTRAINT [pk_Equipment_main] PRIMARY KEY CLUSTERED ([eq_key]) ON [PRIMARY]
GO
