CREATE TABLE [eam].[parts_movement_min_max_w_equip_no]
(
[part_min_max_key] [bigint] NOT NULL IDENTITY(1, 1),
[PrimaryBinID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IsObsolete] [int] NOT NULL,
[IsTBD] [int] NOT NULL,
[PART_part_no] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[part_suffix] [int] NULL,
[part_no_suffix] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[part_no_yyyymm] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PartShortDescription] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductCategoryID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DescriptionAdded] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Keyword] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PartNoDesc] [varchar] (143) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[count_year] [int] NULL,
[count_month] [int] NULL,
[year_mo] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[month_date] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[month_name] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EQTYP_equip_type] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[receipt_qty] [int] NULL,
[issue_qty] [int] NULL,
[transfer_in_qty] [int] NULL,
[transfer_out_qty] [int] NULL,
[adjustment_qty] [int] NULL,
[qty_out_for_repair] [int] NULL,
[qty_repaired] [int] NULL,
[count_wo] [int] NULL,
[RT_qty_issued_life] [int] NULL,
[RT_qty_used_life] [int] NULL,
[RT_receipt_qty] [int] NULL,
[RT_issue_qty] [int] NULL,
[RT_transfer_in_qty] [int] NULL,
[RT_transfer_out_qty] [int] NULL,
[RT_adjustment_qty] [int] NULL,
[RT_rcpt_minus_issued] [int] NULL,
[RT_sum_part_movement] [int] NULL,
[RT_count_wo] [int] NULL,
[TotalQuantityOnOrderForAllLoc] [int] NULL,
[QuantityOnHand] [int] NULL,
[On Hand Plus On Order] [int] NULL,
[SafetyStockLevel] [int] NOT NULL,
[MinimumAvailableQuantity] [int] NOT NULL,
[MaximumAvailableQuantity] [int] NOT NULL,
[Stock Status] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__parts_mov__recor__749F34E9] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
ALTER TABLE [eam].[parts_movement_min_max_w_equip_no] ADD CONSTRAINT [PK_parts_movement_min_max_equip_no] PRIMARY KEY CLUSTERED ([part_min_max_key]) ON [PRIMARY]
GO
