CREATE TABLE [eam].[eq_main_stage]
(
[eq_equip_no] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROCST_proc_status] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EQCAT_equip_category] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOC_assign_pm_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOC_assign_repr_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOC_stored_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_dept_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CPY_company_code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLASS_class_maint] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLASS_class_meter] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLASS_class_pm] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLASS_class_shop_sch] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLASS_class_rental] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLASS_class_stds] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[license_no] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[asset_no] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pm_prog_type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FLT_fleet_no] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACAT_category_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[asset_type] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[X_datetime_update] [datetime] NULL,
[X_datetime_insert] [datetime] NULL,
[ETLProcessActivityID] [int] NOT NULL,
[Processed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__eq_main_processed] DEFAULT ('N'),
[life_total_meter_1] [int] NULL,
[EQTYP_equip_type] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[year] [int] NULL,
[manufacturer] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[model] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sla_status] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_order_status] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fuel_card_no] [int] NULL,
[months_in_operation] [int] NULL,
[deprec_months_life] [int] NULL,
[depr_mths_remaining] [int] NULL,
[record_create_date] [datetime] NULL CONSTRAINT [DF__eq_main_record_create_date] DEFAULT (getdate()),
[shop_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DB_ACC] [int] NULL,
[row_id] [int] NULL,
[LOC_assgn_mobile_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assoc_equip_no] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POOLTYP_veh_type] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[serial_no] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[meter_1_type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[meter_2_type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[license_st] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPER_oper_no] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oper_name] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status_codes] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[radio_no] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cost_center] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_code] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCT_acct_code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[approval_level] [decimal] (12, 2) NULL,
[PRI_shop_priority] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ready_disposition] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOC_station_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parking_stall] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comment_area] [varchar] (1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[title] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[authorization_no] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[original_cost] [decimal] (12, 2) NULL,
[est_replace_cost] [decimal] (12, 2) NULL,
[est_replace_yr] [int] NULL,
[est_replace_mo] [int] NULL,
[replace_code] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_added] [datetime] NULL,
[delivery_date] [datetime] NULL,
[in_service_date] [datetime] NULL,
[meter_1_at_delivery] [int] NULL,
[meter_2_at_delivery] [int] NULL,
[meter_1_prev_total] [int] NULL,
[meter_2_prev_total] [int] NULL,
[own_lease_customer] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[monthly_rent] [decimal] (12, 2) NULL,
[lease_expiration_dt] [datetime] NULL,
[fixed_monthly_cost] [decimal] (12, 2) NULL,
[orig_regist_date] [datetime] NULL,
[regist_expire_date] [datetime] NULL,
[retire_date] [datetime] NULL,
[sale_date] [datetime] NULL,
[disposal_method] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[buy_back] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EQ_replaced_by_unit] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EQ_replacing_unit] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_pm_sched_date] [datetime] NULL,
[last_pm_start_date] [datetime] NULL,
[next_pm_sched_date] [datetime] NULL,
[inspection_month] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stat_inspect_month] [int] NULL,
[stat_inspect_year] [int] NULL,
[stat_inspect_interv] [int] NULL,
[last_pm_slot] [int] NULL,
[next_pm_slot] [int] NULL,
[last_pm_meter_1] [int] NULL,
[last_pm_meter_2] [int] NULL,
[pm_meter_1_interval] [int] NULL,
[pm_meter_2_interval] [int] NULL,
[pm_fuel_override] [int] NULL,
[pm_fuel_since_last] [decimal] (12, 1) NULL,
[oil_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tire_type] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qty_open_work_orders] [int] NULL,
[qty_tires] [int] NULL,
[last_meter_1_reading] [int] NULL,
[last_meter_2_reading] [int] NULL,
[last_meter_1_date] [datetime] NULL,
[last_meter_2_date] [datetime] NULL,
[last_meter_source] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOC_last_fuel_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usage_ticket_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[off_road_use] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[off_road_pct] [int] NULL,
[depreciation_method] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[depr_cur_decline_bal] [decimal] (12, 2) NULL,
[salvage_value] [int] NULL,
[LOC_reserv_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reserv_status] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_reserv_date_out] [datetime] NULL,
[last_reserv_date_in] [datetime] NULL,
[last_reserv_mtr_out] [int] NULL,
[last_reserv_meter_in] [int] NULL,
[exception_switches] [varchar] (104) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cost_rpt_excl_switch] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[excp_rpt_excl_switch] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inv_list_excl_switch] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fixed_insurance_cost] [decimal] (12, 2) NULL,
[fixed_replace_cost] [decimal] (12, 2) NULL,
[fixed_licensing_cost] [decimal] (12, 2) NULL,
[fixed_cost_other_1] [decimal] (12, 2) NULL,
[fixed_cost_other_2] [decimal] (12, 2) NULL,
[fixed_cost_other_3] [decimal] (12, 2) NULL,
[TAX_tax_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[salvage_value_pct] [decimal] (12, 1) NULL,
[repl_cost_computed] [int] NULL,
[repl_cost_recov_year] [int] NULL,
[repl_cst_totrcov_yr] [int] NULL,
[repl_cst_totrcov_lif] [int] NULL,
[ACCT_rev_acct_code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_pm_notify_dept] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[capital_cost_posted] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_orders_ok] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fuel_tickets_ok] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usage_tickets_ok] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[max_meter_1_value] [int] NULL,
[max_meter_2_value] [int] NULL,
[cur_oper_is_first] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[base_mrp_cost] [decimal] (12, 2) NULL,
[actual_company_cost] [decimal] (12, 2) NULL,
[base_mrp_first_oper] [decimal] (12, 2) NULL,
[actual_co_first_oper] [decimal] (12, 2) NULL,
[shipping_cost] [decimal] (12, 2) NULL,
[duty_cost] [decimal] (12, 2) NULL,
[vat_cost] [decimal] (12, 2) NULL,
[LOC_current_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[on_temp_loan] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_temp_loaned_to] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[temp_loan_date] [datetime] NULL,
[disposal_reason] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[transferee_name] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[transferee_address1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[transferee_address2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[transferee_address3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[transferee_address4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INS_insurance_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[order_date] [datetime] NULL,
[planned_deliv_date] [datetime] NULL,
[planned_insvc_date] [datetime] NULL,
[planned_retir_date] [datetime] NULL,
[capitalized_value] [decimal] (12, 2) NULL,
[capitalized_date] [datetime] NULL,
[o_license_date] [datetime] NULL,
[disposal_authority] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[disposal_comment] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[green_disk_no] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[planned_licpl_date] [datetime] NULL,
[lic_plating_no] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[has_tachograph] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dielectric_testing] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[est_meter_at_replace] [int] NULL,
[user_status_1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[user_status_2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[user_status_3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[study_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[outfitting_cost] [decimal] (12, 2) NULL,
[outfitting_effort] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_regular_insp_dt] [datetime] NULL,
[last_statute_insp_dt] [datetime] NULL,
[last_oil_change_date] [datetime] NULL,
[last_oil_change_mtr1] [int] NULL,
[last_oil_change_mtr2] [int] NULL,
[life_total_meter_2] [int] NULL,
[license_no_2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[meter_posting_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_fuel_date] [datetime] NULL,
[last_yardck_datetime] [datetime] NULL,
[yardck_avail_repair] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_test_equip] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOC_access_rts_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comment_area_msg] [varchar] (240) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[class_class_bench] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[file_path] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[file_description] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_asset] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parent_life_meter_1] [int] NULL,
[track_parent_meter] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref_equip_pos] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LEASE_lease_id] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lease_residual_value] [decimal] (12, 2) NULL,
[currency_row_id] [smallint] NULL,
[EQ_equip_no_new] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eq_invalidated] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[any_fuel_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pm_pref_shift] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sale_price] [decimal] (14, 2) NULL,
[LOC_sla_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RESV_last_reserv_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[radio_vehicle_loc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[radio_building_loc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[radio_other_loc] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYSGR_system_grouping] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_pm_start_meter_1] [int] NULL,
[last_pm_start_meter_2] [int] NULL,
[last_meter_2_source] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [eam].[eq_main_stage] ADD CONSTRAINT [pk_eq_main_stage] PRIMARY KEY CLUSTERED ([eq_equip_no], [ETLProcessActivityID]) ON [PRIMARY]
GO
