CREATE TABLE [hastus].[employee_team_number_source]
(
[object] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[emp_identifier] [smallint] NOT NULL,
[emp_last_name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[emp_first_name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[emp_address1] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_address2] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_address3] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_birth_date] [date] NOT NULL,
[start_date] [date] NOT NULL,
[emp_seniority] [date] NOT NULL,
[emp_seniority_ext] [tinyint] NOT NULL,
[emp_licence_no] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_licence_expir] [date] NULL,
[emp_licence_medical] [date] NULL,
[emp_probation_start] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_probation_end] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_tel_ext1] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_telephone2] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_tel_ext2] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_tel_ext3] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_telephone4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_tel_ext4] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_email] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[emp_ltd_email] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[emp_notify_by_email] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_team] [tinyint] NOT NULL,
[emp_access_card_id] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_end_employment_date] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_end_employment_reason] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_sso_identifier] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
