CREATE TABLE [hastus].[bsi_detail]
(
[bsi_poster_detail_key] [bigint] NOT NULL IDENTITY(1, 1),
[trp_number] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trp_int_number] [int] NOT NULL,
[trp_oper_days_12] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[rte_version] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[rte_identifier] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[rte_description] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpat_external_id] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trppt_stop_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trppt_arrival_time] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trp_note_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trp_second_note_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trppt_tp_note_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trppt_tstp_note_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DateCscBooking] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[file_row_id] [int] NOT NULL,
[tpat_route] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpat_direction] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpat_veh_display] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpat_in_serv] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpat_via] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[via_desc] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpatpt_stop_id] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpatpt_load_place] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpatpt_veh_display_code] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpatpt_is_timing_point] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[time_from_point] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plc_description] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[poster_description] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__bsi_detai__recor__27AAD4C4] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
