CREATE TABLE [hastus].[temp_trip_converted_nulls]
(
[vscver_id] [int] NOT NULL,
[trip_no] [int] NOT NULL,
[trip_id] [varchar] (8) COLLATE SQL_Latin1_General_CP850_CI_AS NOT NULL,
[route_id] [varchar] (5) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[route_id_trimmed] [varchar] (5) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[rvariant_id] [varchar] (8) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[direction] [int] NULL,
[start_place] [varchar] (6) COLLATE SQL_Latin1_General_CP850_CI_AS NOT NULL,
[end_place] [varchar] (6) COLLATE SQL_Latin1_General_CP850_CI_AS NOT NULL,
[start_time] [int] NOT NULL,
[end_time] [int] NOT NULL,
[min_lay_start] [int] NULL,
[min_lay_end] [int] NULL,
[distance] [int] NULL,
[trip_type] [int] NOT NULL,
[created_by] [int] NOT NULL,
[event] [varchar] (6) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[event_variation] [int] NULL,
[garage_id] [varchar] (6) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[protect] [bit] NOT NULL,
[note] [varchar] (8) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[public_info] [bit] NOT NULL,
[trip_ref_no] [int] NULL,
[shift_earlier] [int] NOT NULL,
[shift_later] [int] NOT NULL,
[special] [bit] NOT NULL,
[travel] [bit] NOT NULL,
[valid_sun] [bit] NOT NULL,
[valid_mon] [bit] NOT NULL,
[valid_tue] [bit] NOT NULL,
[valid_wed] [bit] NOT NULL,
[valid_thu] [bit] NOT NULL,
[valid_fri] [bit] NOT NULL,
[valid_sat] [bit] NOT NULL,
[tpattern_id] [int] NULL,
[veh_disp_code] [varchar] (8) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[build_time] [int] NOT NULL,
[event_status] [varchar] (2) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[note_2] [varchar] (8) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[original_trip_no] [int] NOT NULL,
[replace_trip_no] [int] NULL,
[is_cancelled] [bit] NOT NULL,
[blocking_gar_id] [varchar] (6) COLLATE SQL_Latin1_General_CP850_CI_AS NULL,
[rpattern_id] [int] NULL,
[sysrecno] [bigint] NOT NULL,
[tbldp_no] [int] NULL,
[rv_id] [varchar] (8) COLLATE SQL_Latin1_General_CP850_CI_AS NOT NULL
) ON [PRIMARY]
GO
