CREATE TABLE [hastus].[avl_ppat]
(
[avl_ppat_key] [bigint] NOT NULL IDENTITY(1, 1),
[filedate] [date] NULL,
[file_row_id] [int] NULL,
[trp_route] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trp_direction] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trp_direction2] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_dir] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded6] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded7] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded8] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded9] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded10] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded11] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded12] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded13] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded14] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded15] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded16] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded17] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded18] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded19] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded20] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded21] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded22] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded23] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded24] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded25] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded26] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded27] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded28] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded29] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded30] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded31] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded32] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded33] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded34] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded35] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded36] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded37] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded38] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded39] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded40] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded41] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded42] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded43] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded44] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded45] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded46] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded47] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded48] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded49] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded50] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded51] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded52] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded53] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oa_rte_main_ppat_plc_padded54] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__avl_ppat__record__540879EF] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
