CREATE TABLE [hastus].[bay_use_eugeneStation]
(
[booking_bay_use_key] [int] NOT NULL IDENTITY(1, 1),
[booking_id] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[depart] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hr_grp] [int] NULL,
[sched_type_id] [smallint] NULL,
[10LIN_A] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[10LIN_B] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[11D] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[A] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[B] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[C] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[D] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[G] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[H] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[I] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[J] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[K] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[N] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[O] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OSD] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[R] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[S] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[T] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[U] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[10LIN_A_lo] [int] NULL,
[10LIN_B_lo] [int] NULL,
[11D_lo] [int] NULL,
[A_lo] [int] NULL,
[B_lo] [int] NULL,
[C_lo] [int] NULL,
[D_lo] [int] NULL,
[E_lo] [int] NULL,
[F_lo] [int] NULL,
[G_lo] [int] NULL,
[H_lo] [int] NULL,
[I_lo] [int] NULL,
[J_lo] [int] NULL,
[K_lo] [int] NULL,
[L_lo] [int] NULL,
[LIN_lo] [int] NULL,
[M_lo] [int] NULL,
[N_lo] [int] NULL,
[O_lo] [int] NULL,
[OSD_lo] [int] NULL,
[P_lo] [int] NULL,
[Q_lo] [int] NULL,
[R_lo] [int] NULL,
[S_lo] [int] NULL,
[T_lo] [int] NULL,
[U_lo] [int] NULL,
[10lin_a_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[10lin_b_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[11d_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[a_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[b_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[c_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[d_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[e_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[f_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[g_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[h_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[i_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[j_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[k_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[l_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[lin_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[m_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[n_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[o_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[osd_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[p_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[q_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[r_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[s_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[u_back] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[10lin_a_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[10lin_b_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[11d_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[a_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[b_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[c_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[d_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[e_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[f_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[g_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[h_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[i_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[j_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[k_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[l_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[lin_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[m_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[n_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[o_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[osd_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[p_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[q_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[r_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[s_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[u_font] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__bay_use_e__recor__5095E17C] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
ALTER TABLE [hastus].[bay_use_eugeneStation] ADD CONSTRAINT [PK_bay_use_eugeneStation] PRIMARY KEY CLUSTERED ([booking_bay_use_key]) ON [PRIMARY]
GO
