CREATE TABLE [hastus].[trip_stop_route_time_source_prepared]
(
[trip_rte_time_key] [bigint] NOT NULL IDENTITY(1, 1),
[RankInTimetable] [bigint] NOT NULL,
[RankInTimeTablePlace] [bigint] NULL,
[DateCscBooking] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateVscType] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCscTypeTitle] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCscScen] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpat_route] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rte_description] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpat_direction] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpatpt_load_place] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpatpt_is_timing_point] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpatpt_stop_id] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tstp_passing_time] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_stop_arrival_time_result] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_stop_arrival_time_ampm] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tpat_via] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[via_desc] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tpat_external_id] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plc_description] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trp_int_number] [int] NULL,
[trp_number] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trp_operating_days] [nvarchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trp_type] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trp_type_code] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trp_is_special] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trp_is_public] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_description] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_place] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loca_intersect_1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loca_intersect_2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_district] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_zone] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_is_public] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trp_note_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trp_second_note_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trppt_tp_note_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trppt_tstp_note_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trp_note_txt] [varchar] (3500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trp_second_note_txt] [varchar] (3500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trppt_tp_note_txt] [varchar] (3500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trppt_tstp_note_txt] [varchar] (3500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__trip_stop__recor__0F143124] DEFAULT (sysdatetime())
) ON [PRIMARY]
GO
