CREATE TABLE [itk].[Employee]
(
[EmployeeGUID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_Employee_EmployeeGUID] DEFAULT (newid()),
[PropertyGUID] [uniqueidentifier] NOT NULL,
[FirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MiddleName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StreetAddress] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SocialSecurityNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfBirth] [datetime] NULL,
[EmergencyNotify] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LogonName] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployeeID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupervisorLevel] [int] NOT NULL,
[DateHired] [datetime] NOT NULL,
[DateFired] [datetime] NULL,
[DateOfSeniority] [datetime] NULL,
[GamingCardNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GamingCardExpiryDate] [datetime] NULL,
[MondayOff] [bit] NOT NULL,
[TuesdayOff] [bit] NOT NULL,
[WednesdayOff] [bit] NOT NULL,
[ThursdayOff] [bit] NOT NULL,
[FridayOff] [bit] NOT NULL,
[SaturdayOff] [bit] NOT NULL,
[SundayOff] [bit] NOT NULL,
[GamingRelated] [bit] NOT NULL CONSTRAINT [DF_Employee_GamingRelated] DEFAULT ((0)),
[Country] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobPosition] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shift] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Exclusive] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Password] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherSkills] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimeStamp] [timestamp] NULL,
[DateCreated] [datetime] NOT NULL,
[DateModified] [datetime] NOT NULL,
[SupervisorGUID] [uniqueidentifier] NULL,
[Division] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Height] [int] NULL,
[Weight] [decimal] (18, 4) NULL,
[ShiftStart] [datetime] NULL,
[ShiftEnd] [datetime] NULL,
[CellPhoneNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryLanguageSpoken] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaritalStatus] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BestAssetGUID] [uniqueidentifier] NULL,
[ModifiedBy] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessPhoneNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessFaxNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailCode] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comments] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockForAPI] [bit] NOT NULL CONSTRAINT [DF_Employee_LockForAPI] DEFAULT ((0)),
[Custom1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsGlobal] [bit] NOT NULL CONSTRAINT [DF__Employee__IsGlob__65CC03DF] DEFAULT ((0)),
[DriversLicenseNum] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HairColour] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EyeColour] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PassportNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WebAddress] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployeeAutoID] [int] NOT NULL IDENTITY(1, 1),
[Owner] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerDepartmentGUID] [uniqueidentifier] NULL CONSTRAINT [DF_Employee_OwnerDepartmentGUID] DEFAULT ('381241AE-833D-4736-9554-01745ED6C083'),
[CreatedBy] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneNumber_Enc] [varbinary] (200) NULL,
[SocialSecurityNumber_Enc] [varbinary] (300) NULL,
[DateOfBirth_Enc] [varbinary] (100) NULL,
[DriversLicenseNum_Enc] [varbinary] (300) NULL,
[PassportNumber_Enc] [varbinary] (600) NULL,
[LockedFields] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PoliceClearance] [bit] NOT NULL CONSTRAINT [DF_Employee_PoliceClearance] DEFAULT ((0)),
[WorkPermit] [bit] NOT NULL CONSTRAINT [DF_Employee_WorkPermit] DEFAULT ((0)),
[GamingLicense] [bit] NOT NULL CONSTRAINT [DF_Employee_GamingLicense] DEFAULT ((0)),
[OtherLicense] [bit] NOT NULL CONSTRAINT [DF_Employee_OtherLicense] DEFAULT ((0)),
[BackgroundCheck] [bit] NOT NULL CONSTRAINT [DF_Employee_BackgroundCheck] DEFAULT ((0)),
[PoliceClearanceIssueDate] [datetime] NULL,
[PoliceClearanceExpiryDate] [datetime] NULL,
[WorkPermitIssueDate] [datetime] NULL,
[WorkPermitExpiryDate] [datetime] NULL,
[GamingLicenseIssueDate] [datetime] NULL,
[GamingLicenseExpiryDate] [datetime] NULL,
[OtherLicenseIssueDate] [datetime] NULL,
[OtherLicenseExpiryDate] [datetime] NULL,
[BackgroundCheckDatePerformed] [datetime] NULL,
[BackgroundCheckNextReviewDate] [datetime] NULL,
[BackgroundCheckConductedByGUID] [uniqueidentifier] NULL,
[BackgroundCheckReviewedByGUID] [uniqueidentifier] NULL,
[Deposit] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackgroundCheckNotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackgroundCheckList] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubjectGUID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [itk].[Employee] ADD CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED ([EmployeeAutoID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [itk].[Employee] ADD CONSTRAINT [UQ_Employee_EmployeeGUID] UNIQUE NONCLUSTERED ([EmployeeGUID]) WITH (FILLFACTOR=56) ON [PRIMARY]
GO
