CREATE TABLE [model].[ROUTE_DIR_STOP_TP_TRIP_HIST]
(
[RTE_DIR_STOP_KEY_ID] [int] NOT NULL IDENTITY(1, 1),
[TIME_TABLE_VERSION_ID] [int] NOT NULL,
[SERVICE_TYPE_ID] [smallint] NOT NULL,
[ROUTE_ID] [int] NULL,
[ROUTE_DIRECTION_ID] [numeric] (5, 0) NULL,
[GEO_NODE_ID] [numeric] (10, 0) NULL,
[ROUTE_ABBR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROUTE_NAME] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STOP_ABBR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STOP_NAME] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROUTE_DIRECTION_ABBR] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROUTE_DIRECTION_NAME] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROUTE_DIR] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RTE_DIR_STOP_TP_KEY] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RTE_DIR_STOP_TP_TRIP_KEY] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRIP_ID] [int] NULL,
[TRIP_END_TIME] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STOP_LATITUDE] [numeric] (21, 9) NULL,
[STOP_LONGITUDE] [numeric] (21, 9) NULL,
[TIME_POINT_ABBR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIME_POINT_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SIGNIFICANT_TP] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[record_created_date] [datetime2] NOT NULL DEFAULT (sysdatetime())
)
GO
CREATE NONCLUSTERED INDEX [ix_ROUTE_DIR_STOP_TP_TRIP_RTEID_Includes_h] ON [model].[ROUTE_DIR_STOP_TP_TRIP_HIST] ([ROUTE_ID], [TRIP_END_TIME]) INCLUDE ([ROUTE_DIRECTION_ID], [GEO_NODE_ID])
GO
CREATE NONCLUSTERED INDEX [ix_ROUTE_DIR_STOP_TP_TRIP_RTEID_RDIR_GEO_TRIPEND_h] ON [model].[ROUTE_DIR_STOP_TP_TRIP_HIST] ([TIME_TABLE_VERSION_ID], [ROUTE_ID], [ROUTE_DIRECTION_ID], [GEO_NODE_ID], [SERVICE_TYPE_ID], [TRIP_ID])
GO
