CREATE TABLE [ops].[codesHistory]
(
[codeHistoryKey] [int] NOT NULL IDENTITY(1, 1),
[validFrom] [datetime] NOT NULL,
[validTo] [datetime] NULL,
[codeType] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[codeSet] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[codeValue] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[description] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[basicflags] [smallint] NOT NULL,
[flagset1] [smallint] NOT NULL,
[flagset2] [smallint] NOT NULL,
[flagset3] [smallint] NOT NULL,
[flagset4] [smallint] NOT NULL,
[smallint1] [smallint] NULL,
[smallint2] [smallint] NULL,
[smallint3] [smallint] NULL,
[smallint4] [smallint] NULL,
[smallint5] [smallint] NULL,
[smallint6] [smallint] NULL,
[smallint7] [smallint] NULL,
[smallint8] [smallint] NULL,
[int1] [int] NULL,
[int2] [int] NULL,
[onechar1] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[onechar2] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[onechar3] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[onechar4] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fourchar1] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fourchar2] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fourchar3] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fourchar4] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fourchar5] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fourchar6] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fourchar7] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fourchar8] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[codevarchar] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modStampDate] [datetime] NOT NULL,
[modStampUser] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[changeType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__codes_tim__recor__79C4DE09] DEFAULT (sysdatetime())
) ON [PRIMARY]
GO
