CREATE TABLE [ops].[rdo_call_list_full]
(
[rdo_call_list_key] [int] NOT NULL IDENTITY(1, 1),
[operator] [varchar] (67) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[opdate] [date] NULL,
[sen_date] [smalldatetime] NOT NULL,
[sen_lot] [int] NULL,
[fone1] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fonehome] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[fonecell] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[work] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[absence] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[week] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dnc] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_m13] [date] NULL,
[work_m13] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_m12] [date] NULL,
[work_m12] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_m11] [date] NULL,
[work_m11] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_m10] [date] NULL,
[work_m10] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_m09] [date] NULL,
[work_m09] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_m08] [date] NULL,
[work_m08] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_m07] [date] NULL,
[work_m07] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_m06] [date] NULL,
[work_m06] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_m05] [date] NULL,
[work_m05] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_m04] [date] NULL,
[work_m04] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_m03] [date] NULL,
[work_m03] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_m02] [date] NULL,
[work_m02] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_m01] [date] NULL,
[work_m01] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_p01] [date] NULL,
[work_p01] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_p02] [date] NULL,
[work_p02] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[opdate_p03] [date] NULL,
[work_p03] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__rdo_call___recor__0C70FD4F] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
ALTER TABLE [ops].[rdo_call_list_full] ADD CONSTRAINT [PK_rdo_call_list_full] PRIMARY KEY CLUSTERED ([rdo_call_list_key]) ON [PRIMARY]
GO
