CREATE TABLE [pds].[Integration_EmpPerson]
(
[emp_person_id] [int] NOT NULL IDENTITY(1, 1),
[emp_person_status] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[person_id] [int] NULL,
[fullname] [varchar] (210) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[first_name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[middle_name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[middle_initial] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[aka] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[initials] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_id] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gender_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gender] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[company_code] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[company] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[role_code] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[role] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[job_code] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[position_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[organization_code] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[organization] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location_code] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[distribution_code] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[distribution] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_active] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hr_status_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hr_status] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hr_is_active] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hr_status_date] [datetime2] NULL,
[payroll_status_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[payroll_status] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[payroll_is_active] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[payroll_status_date] [datetime2] NULL,
[benefits_status_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[benefits_status] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[benefits_is_active] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[benefits_status_date] [datetime2] NULL,
[payroll_processing_status] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[payroll_processing] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[payroll_processing_is_active] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status_reason_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status_reason] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_factor] [decimal] (7, 4) NULL,
[employee_type] [int] NULL,
[class_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[class] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pay_designator_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pay_designator] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pay_method_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pay_method] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_category_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_category] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[flsa_group_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[flsa_group] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_pension_elig] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hire_date] [datetime2] NULL,
[actual_hire_date] [datetime2] NULL,
[rehire_date] [datetime2] NULL,
[termination_date] [datetime2] NULL,
[review_date] [datetime2] NULL,
[adjusted_service_date] [datetime2] NULL,
[return_date] [datetime2] NULL,
[seniority_date] [datetime2] NULL,
[dist_seniority_date] [datetime2] NULL,
[time_of_hire] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[time_card_indicator_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[time_card_indicator] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shift_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shift] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fiscal_calendar_id] [int] NULL,
[fiscal_calendar] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[normal_hours] [decimal] (6, 2) NULL,
[contract_days] [int] NULL,
[contract_day_hours] [decimal] (5, 2) NULL,
[number_of_pays] [int] NULL,
[last_pay_date] [datetime2] NULL,
[fte] [decimal] (5, 4) NULL,
[position_status_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[position_status] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[position_status_date] [datetime2] NULL,
[position_status_reason_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[position_status_reason] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[person_reason_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[person_reason] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[start_date] [datetime2] NULL,
[end_date] [datetime2] NULL,
[normal_hours_daily] [decimal] (6, 2) NULL,
[role_normal_hours] [decimal] (6, 2) NULL,
[normal_hours_monthly] [decimal] (6, 2) NULL,
[normal_hours_yearly] [decimal] (6, 2) NULL,
[normal_days_weekly] [decimal] (6, 2) NULL,
[normal_days_monthly] [decimal] (6, 2) NULL,
[normal_days_yearly] [decimal] (6, 2) NULL,
[normal_weeks_yearly] [decimal] (6, 2) NULL,
[normal_months_yearly] [decimal] (6, 2) NULL,
[comments] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employment_type] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emp_status_date] [datetime2] NULL,
[record_created_date] [datetime2] NULL CONSTRAINT [DF__Integrati__recor__1362886F] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
ALTER TABLE [pds].[Integration_EmpPerson] ADD CONSTRAINT [PK_Integration_EmpPerson] PRIMARY KEY CLUSTERED ([emp_person_id]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_pds_Integration_EmpPerson_emp_person_status_hr_is_active_Include7] ON [pds].[Integration_EmpPerson] ([emp_person_status], [hr_is_active]) INCLUDE ([person_id], [last_name], [first_name], [employee_id], [job_code], [position_code], [distribution_code]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_Integration_EmpPerson_emp_person_status_hr_is_active_Includes9] ON [pds].[Integration_EmpPerson] ([emp_person_status], [hr_is_active]) INCLUDE ([person_id], [last_name], [first_name], [middle_name], [middle_initial], [aka], [initials], [employee_id], [role]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_Integration_EmpPerson_emp_person_status] ON [pds].[Integration_EmpPerson] ([emp_person_status], [person_id]) ON [PRIMARY]
GO
