CREATE TABLE [pds].[Integration_EmpContact_Stage]
(
[person_id] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_id] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_name] [varchar] (210) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[relationship_code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[relationship] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[area_code1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[phone_no1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[extension1] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[phone_number1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[area_code2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[phone_no2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[extension2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[phone_number2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[area_code3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[phone_no3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[extension3] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[phone_number3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address_line1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address_line2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address_line3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address_line4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[county] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state_name] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip_code] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city_state_zip] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[country_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[country] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[effective_date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_address] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priority] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
