CREATE TABLE [tm].[DW_CALENDAR_SPM]
(
[CAL_SPM_KEY] [bigint] NOT NULL,
[CALENDAR_ID] [numeric] (10, 0) NOT NULL,
[SPM] [int] NOT NULL,
[YYYYMMDD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Calendar Date Time] [datetime2] NOT NULL,
[CALENDAR_DATE] [date] NOT NULL
) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [ix_clusteredOn_DW_CALENDAR_SPM] ON [tm].[DW_CALENDAR_SPM] ([CAL_SPM_KEY], [CALENDAR_ID], [SPM]) ON [PRIMARY]
GO
