CREATE TABLE [tm].[ROUTE_DIRECTION]
(
[ROUTE_DIRECTION_KEY] [int] NOT NULL IDENTITY(1, 1),
[ROUTE_DIRECTION_ID] [numeric] (5, 0) NOT NULL,
[ROUTE_DIRECTION_ABBR] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROUTE_DIRECTION_NAME] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[record_created_date] [datetime2] NULL CONSTRAINT [DF__ROUTE_DIR__recor__206614BF] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
ALTER TABLE [tm].[ROUTE_DIRECTION] ADD CONSTRAINT [PK_ROUTE_DIRECTION] PRIMARY KEY CLUSTERED ([ROUTE_DIRECTION_KEY]) ON [PRIMARY]
GO
