CREATE TABLE [tm].[RADIO_CONFIGURATION]
(
[RADIO_CONFIGURATION_KEY] [int] NOT NULL IDENTITY(1, 1),
[RADIO_CONFIGURATION_ID] [int] NOT NULL,
[NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[record_created_date] [datetime2] NOT NULL CONSTRAINT [DF__RADIO_CON__recor__7CCD305E] DEFAULT (sysdatetime()),
[record_updated_date] [datetime2] NULL
) ON [PRIMARY]
GO
ALTER TABLE [tm].[RADIO_CONFIGURATION] ADD CONSTRAINT [PK_RADIO_CONFIGURATION] PRIMARY KEY CLUSTERED ([RADIO_CONFIGURATION_KEY]) ON [PRIMARY]
GO
