CREATE TABLE [wrk].[stage_CITS_Input]
(
[ID] [int] NULL,
[Received by Number] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Last Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer First Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date Of Incident] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Time of Incident] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Direction of Travel] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location Street] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location Cross Street] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Route Number] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bus Number] [int] NULL,
[Employee Number] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department Code] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Staff Number] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Call Back] [bit] NULL,
[Nature of Incident] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Comments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee Comments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Staff Comments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date of Staff Comments] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date Entered] [datetime] NULL,
[Given to Supervisor] [datetime] NULL,
[NOC] [bit] NULL
) ON [PRIMARY]
GO
