CREATE TABLE [wrk].[apc_projection]
(
[CALENDAR_ID] [numeric] (10, 0) NOT NULL,
[TIME_TABLE_VERSION_ID] [numeric] (5, 0) NOT NULL,
[BLOCK_ID] [numeric] (10, 0) NULL,
[ROUTE_ID] [int] NULL,
[ROUTE_DIRECTION_ID] [numeric] (5, 0) NULL,
[GEO_NODE_ID] [numeric] (10, 0) NULL,
[MESSAGE_TIME] [int] NULL,
[TRIP_ID] [int] NOT NULL,
[HH] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MM] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SS] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BOARD] [int] NULL,
[ALIGHT] [int] NULL,
[DEPARTURE_LOAD] [int] NULL,
[calendar_date] [date] NULL,
[calendar_datetime] [datetime] NULL,
[BLOCK_ABBR] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ROUTE_ABBR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ROUTE_NAME] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ROUTE_DIRECTION_NAME] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[rdir_abbr] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GEO_NODE_ABBR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GEO_NODE_NAME] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[temp] [float] NULL,
[clouds] [float] NULL,
[visibility] [float] NULL,
[wind_speed] [float] NULL,
[isHoliday] [int] NOT NULL,
[DayOfWeekNbr] [int] NULL,
[record_created_date] [datetime2] NOT NULL DEFAULT (sysdatetime())
)
GO
