CREATE TABLE [dbo].[profile_EAM_part_eq_claim]
(
[name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[timestamp] [datetimeoffset] NULL,
[timestamp (UTC)] [datetimeoffset] NULL,
[batch_text] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[session_id] [int] NULL,
[server_principal_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[query_hash] [decimal] (20, 0) NULL,
[nt_username] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[database_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[database_id] [bigint] NULL,
[client_pid] [bigint] NULL,
[client_app_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[event_sequence] [decimal] (20, 0) NULL,
[attach_activity_id_xfer.guid] [uniqueidentifier] NULL,
[attach_activity_id_xfer.seq] [bigint] NULL,
[attach_activity_id.guid] [uniqueidentifier] NULL,
[attach_activity_id.seq] [bigint] NULL,
[cpu_time] [decimal] (20, 0) NULL,
[duration] [decimal] (20, 0) NULL,
[page_server_reads] [decimal] (20, 0) NULL,
[physical_reads] [decimal] (20, 0) NULL,
[logical_reads] [decimal] (20, 0) NULL,
[writes] [decimal] (20, 0) NULL,
[spills] [decimal] (20, 0) NULL,
[row_count] [decimal] (20, 0) NULL,
[result] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_cached] [bit] NULL,
[is_recovered] [bit] NULL,
[is_dac] [bit] NULL,
[connection_reset_option] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[object_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statement] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[data_stream] [varbinary] (max) NULL,
[output_parameters] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[packet_size] [bigint] NULL,
[options] [varbinary] (max) NULL,
[options_text] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_hostname] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[[TextData]]] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
