SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [tm].[wheelchair_deploys]
AS
/********************************

CREATED BY	: B Eichberger
CREATED ON	: 20250521
PURPOSE		: Aid Power BI Reporting on Wheelchair Ramping
			  38543 Report View Request - Wheelchair_Cycle_Count

*/
SELECT cal.[CALENDAR_ID]
,c.[TIME_TABLE_VERSION_ID]
,v.TIME_TABLE_VERSION_NAME
,c.[ROUTE_ID]
,c.[ROUTE_DIRECTION_ID]
,r.ROUTE_ABBR
,r.ROUTE_NAME
,c.[GEO_NODE_ID]
,gn.GEO_NODE_ABBR
,gn.GEO_NODE_NAME
,c.[OPERATOR_ID]
,c.[RUN_ID]
,rn.RUN_DESIGNATOR
,c.[VEHICLE_ID]
,vh.PROPERTY_TAG vehicle_number
,c.[BLOCK_ID]
,b.BLOCK_ABBR
,c.[TRIP_ID]
,t.TRIP_END_TIME
,TRIP_END_HHMM = dbo.ConvertTimeToHHMMSS(t.TRIP_END_TIME,'second')
,c.[SERVICE_TYPE_ID]
,st.SERVICE_ABBR
,st.SERVICE_TYPE_TEXT
,c.[TIME_POINT_ID]
,tp.TIME_POINT_ABBR
,tp.TIME_PT_NAME
,c.[REVENUE_ID]
,rv.REVENUE_DESCRIPTION
,c.[BLOCK_STOP_ORDER]
,c.[LATITUDE]
,c.[LONGITUDE]
,c.[MESSAGE_TIME]
,MSG_TIME = dbo.ConvertTimeToHHMMSS(c.[MESSAGE_TIME],'second')
,c.[ODOMETER]
,c.[IS_GARAGE]
FROM [LTD-TMDATA].[tmdatamart].[dbo].[WHEELCHAIR_CYCLED_COUNT] c
JOIN ltd_dw.tm.dw_calendar cal ON cal.calendar_id = c.CALENDAR_ID
	 JOIN [LTD-TMDATA].tmdatamart.dbo.TIME_TABLE_VERSION v ON v.TIME_TABLE_VERSION_ID = c.TIME_TABLE_VERSION_ID
	 JOIN [LTD-TMDATA].tmdatamart.dbo.ROUTE r ON r.ROUTE_ID = c.ROUTE_ID
	 JOIN [LTD-TMDATA].tmdatamart.dbo.ROUTE_DIRECTION rd ON rd.ROUTE_DIRECTION_ID = c.ROUTE_DIRECTION_ID 
	 JOIN [LTD-TMDATA].tmdatamart.dbo.BLOCK b ON b.BLOCK_ID = c.BLOCK_ID AND b.TIME_TABLE_VERSION_ID = c.TIME_TABLE_VERSION_ID
	 JOIN [LTD-TMDATA].tmdatamart.dbo.TRIP t ON t.TRIP_ID = c.TRIP_ID
	 JOIN [LTD-TMDATA].tmdatamart.dbo.SERVICE_TYPE st ON st.SERVICE_TYPE_ID = c.SERVICE_TYPE_ID
	 JOIN [LTD-TMDATA].tmdatamart.dbo.TIME_POINT tp ON tp.TIME_POINT_ID = c.TIME_POINT_ID 
	 JOIN [LTD-TMDATA].tmdatamart.dbo.REVENUE rv ON rv.REVENUE_ID = c.REVENUE_ID
	 JOIN [LTD-TMDATA].tmdatamart.dbo.RUN rn ON rn.RUN_ID = c.RUN_ID
	 JOIN [LTD-TMDATA].tmdatamart.dbo.GEO_NODE gn ON gn.GEO_NODE_ID = c.GEO_NODE_ID
	 JOIN [LTD-TMDATA].tmdatamart.dbo.VEHICLE vh ON vh.VEHICLE_ID = c.VEHICLE_ID
WHERE cal.CALENDAR_ID > 120180000
GO
