CREATE TABLE [webstore].[Order]
(
[DWOrderKey] [int] NOT NULL IDENTITY(1, 1),
[ID] [bigint] NOT NULL,
[ParentID] [bigint] NULL,
[Status] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Version] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PricesIncludeTax] [bit] NULL,
[DateCreated] [datetime] NULL,
[DateModified] [datetime] NULL,
[DiscountTotal] [decimal] (18, 2) NULL,
[DiscountTax] [decimal] (18, 2) NULL,
[ShippingTotal] [decimal] (18, 2) NULL,
[ShippingTax] [decimal] (18, 2) NULL,
[CartTax] [decimal] (18, 2) NULL,
[Total] [decimal] (18, 2) NULL,
[TotalTax] [decimal] (18, 2) NULL,
[CustomerID] [bigint] NULL,
[OrderKey] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipping] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentMethod] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentMethodTitle] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerIpAddress] [nvarchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerUserAgent] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedVia] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerNote] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCompleted] [datetime] NULL,
[DatePaid] [datetime] NULL,
[CartHash] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MetaData] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LineItems] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxLines] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingLines] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FeeLines] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponLines] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Refunds] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentUrl] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsEditable] [bit] NULL,
[NeedsPayment] [bit] NULL,
[NeedsProcessing] [bit] NULL,
[DateCreatedGmt] [datetime] NULL,
[DateModifiedGmt] [datetime] NULL,
[DateCompletedGmt] [datetime] NULL,
[DatePaidGmt] [datetime] NULL,
[CurrencySymbol] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Links] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EtlProcessActivityID] [int] NULL,
[ApiRequestID] [int] NULL,
[RecordCreatedDate] [datetime] NOT NULL DEFAULT (getdate()),
[RecordUpdatedDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [webstore].[Order] ADD PRIMARY KEY CLUSTERED ([DWOrderKey]) ON [PRIMARY]
GO
