SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

------------------LTD_GLOSSARY---------------
-- created by:	Sopheap Suy
-- created dt:  9/25/2023
-- purpose	 :  view for reporting
-- use       :  select * from tm.[VIEW_STORE_PASS_v] 
--				view for all pasenger count data from 2013 forward


CREATE VIEW [tm].[VIEW_STORE_PASS_v]
AS
SELECT [calendar_id]
      ,[calendar_date]
      ,[block]
      ,[block_numeric]
      ,[msg_time]
      ,[msg_time_spm]
      ,[msg_time_sql]
      ,[route]
      ,[dir]
      ,[rte_and_dir]
      ,[rte_public]
      ,[rte_rural]
      ,[emx_block]
      ,[rev_rte]
      ,[pattern_id]
      ,[pattern]
      ,[geo_node_id]
      ,[stop]
      ,[stop_name]
      ,[college]
      ,[brt_asso_stop]
      ,[brt_segment]
      ,[brt_seg_offs]
      ,[pc_latitude]
      ,[pc_longitude]
      ,[gn_latitude]
      ,[gn_longitude]
      ,[distance_delta_pc_and_gn]
      ,[operator_id]
      ,[badge]
      ,[operator_first]
      ,[operator_last]
      ,[operator]
      ,[operators_supervisor]
      ,[run]
      ,[the_bus]
      ,[veh]
      ,[bus_class]
      ,[artic]
      ,[electric]
      ,[emx_bus]
      ,[veh_text]
      ,[ttv_id]
      ,[ttv]
      ,[bid]
      ,[service_type_text]
      ,[service_type_general]
      ,[trip_id]
      ,[trip_sn]
      ,[trip_seq]
      ,[blk_trp_seq]
      ,[trip_end]
      ,[trip_end_time]
      ,[block_stop_order]
      ,[board]
      ,[alight]
      ,[run_load]
      ,[passenger_miles]
      ,[departure_load]
      ,[odometer]
      ,[overload_id]
      ,[revenue_id]
      ,[passenger_count_id]
      ,[pc_happened]
      ,[confidence]
      ,[confidence_between_100_and_1000_meters]
      ,[confidence_off_route]
      ,[confidence_out_of_sequence]
      ,[confidence_prior_tp_missed]
      ,[confidence_used_mobile_msgs_stop_offset]
      ,[time_point_id]
      ,[FIRST_DOOR_OPEN_TIME]
      ,[LAST_DOOR_CLOSED_TIME]
      ,[work_piece_id]
      ,[isOverload]
      ,[record_created_date]
  FROM [ltd_dw].[tm].[VIEW_STORE_PASS]
UNION ALL

SELECT [calendar_id]
      ,[calendar_date]
      ,[block]
      ,[block_numeric]
      ,[msg_time]
      ,[msg_time_spm]
      ,[msg_time_sql]
      ,[route]
      ,[dir]
      ,[rte_and_dir]
      ,[rte_public]
      ,[rte_rural]
      ,[emx_block]
      ,[rev_rte]
      ,[pattern_id]
      ,[pattern]
      ,[geo_node_id]
      ,[stop]
      ,[stop_name]
      ,[college]
      ,[brt_asso_stop]
      ,[brt_segment]
      ,[brt_seg_offs]
      ,[pc_latitude]
      ,[pc_longitude]
      ,[gn_latitude]
      ,[gn_longitude]
      ,[distance_delta_pc_and_gn]
      ,[operator_id]
      ,[badge]
      ,[operator_first]
      ,[operator_last]
      ,[operator]
      ,[operators_supervisor]
      ,[run]
      ,[the_bus]
      ,[veh]
      ,[bus_class]
      ,[artic]
      ,[electric]
      ,[emx_bus]
      ,[veh_text]
      ,[ttv_id]
      ,[ttv]
      ,[bid]
      ,[service_type_text]
      ,[service_type_general]
      ,[trip_id]
      ,[trip_sn]
      ,[trip_seq]
      ,[blk_trp_seq]
      ,[trip_end]
      ,[trip_end_time]
      ,[block_stop_order]
      ,[board]
      ,[alight]
      ,[run_load]
      ,[passenger_miles]
      ,[departure_load]
      ,[odometer]
      ,[overload_id]
      ,[revenue_id]
      ,[passenger_count_id]
      ,[pc_happened]
      ,[confidence]
      ,[confidence_between_100_and_1000_meters]
      ,[confidence_off_route]
      ,[confidence_out_of_sequence]
      ,[confidence_prior_tp_missed]
      ,[confidence_used_mobile_msgs_stop_offset]
      ,[time_point_id]
      ,[FIRST_DOOR_OPEN_TIME]
      ,[LAST_DOOR_CLOSED_TIME]
      ,[work_piece_id]
      ,[isOverload]
      ,[record_created_date]
  FROM [ltd_dw].[tm].[VIEW_STORE_PASS_Archive]
GO
