SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [hastus].[updatePosterSources]
AS

/*------------------LTD_GLOSSARY---------------
UPDATED BY:	Sopheap Suy
UPDATED DT:  10/31/2024
purpose	 :  Add object activities on who, what, when call this object
			write this data to aud.object_activity table everytime it's called */

SET NOCOUNT ON

DECLARE @SPROC VARCHAR(100)
SET @SPROC = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID)

INSERT INTO DBA.[aud].[Object_Activity]
	([server_name], [database_name] ,[host_name], [System_User], [object_name]
	,[client_net_address], [local_net_address], [auth_Scheme], [last_read], [last_write]
	,[most_recent_sql_handle], [Timestamp], object_type)
SELECT DISTINCT @@SERVERNAME, DB_NAME(),HOST_NAME(),SYSTEM_USER, @SPROC,
	client_net_address, local_net_address , auth_Scheme, last_read, last_write 
	,most_recent_sql_handle, CURRENT_TIMESTAMP AS [Timestamp], 'PROC'
FROM sys.dm_exec_connections 
WHERE session_id = @@SPID ;

TRUNCATE TABLE hastus.temp_public_footnotes
TRUNCATE TABLE hastus.footnotes_in_spanish	
TRUNCATE TABLE hastus.temp_trip_converted_nulls
TRUNCATE TABLE hastus.temp_PosterViewOne
TRUNCATE TABLE hastus.temp_PosterViewTwo
TRUNCATE TABLE hastus.temp_PosterViewThree
TRUNCATE TABLE hastus.temp_PosterViewThreeA
TRUNCATE TABLE hastus.temp_PosterViewThreeB
TRUNCATE TABLE hastus.temp_PosterViewFour

INSERT hastus.footnotes_in_spanish(
[unique_id],
[note_id],
[note_text])
SELECT [unique_id],
[note_id],
[note_text] FROM [LTD-HASTUS2].hastus_ltd.dbo.footnotes_in_spanish

INSERT hastus.temp_public_footnotes(
[note_id]
      ,[text_length]
      ,[footnote_text])
SELECT [note_id]
      ,[text_length]
      ,[footnote_text]
  FROM [hastus].[ltd_public_footnotes]

INSERT [hastus].[temp_trip_converted_nulls]
(
[vscver_id]
,[trip_no]
,[trip_id]
,[route_id]
,[route_id_trimmed]
,[rvariant_id]
,[direction]
,[start_place]
,[end_place]
,[start_time]
,[end_time]
,[min_lay_start]
,[min_lay_end]
,[distance]
,[trip_type]
,[created_by]
,[event]
,[event_variation]
,[garage_id]
,[protect]
,[note]
,[public_info]
,[trip_ref_no]
,[shift_earlier]
,[shift_later]
,[special]
,[travel]
,[valid_sun]
,[valid_mon]
,[valid_tue]
,[valid_wed]
,[valid_thu]
,[valid_fri]
,[valid_sat]
,[tpattern_id]
,[veh_disp_code]
,[build_time]
,[event_status]
,[note_2]
,[original_trip_no]
,[replace_trip_no]
,[is_cancelled]
,[blocking_gar_id]
,[rpattern_id]
,[sysrecno]
,[tbldp_no]
,[rv_id])
SELECT [vscver_id]
      ,[trip_no]
      ,[trip_id]
      ,[route_id]
      ,[route_id_trimmed]
      ,[rvariant_id]
      ,[direction]
      ,[start_place]
      ,[end_place]
      ,[start_time]
      ,[end_time]
      ,[min_lay_start]
      ,[min_lay_end]
      ,[distance]
      ,[trip_type]
      ,[created_by]
      ,[event]
      ,[event_variation]
      ,[garage_id]
      ,[protect]
      ,[note]
      ,[public_info]
      ,[trip_ref_no]
      ,[shift_earlier]
      ,[shift_later]
      ,[special]
      ,[travel]
      ,[valid_sun]
      ,[valid_mon]
      ,[valid_tue]
      ,[valid_wed]
      ,[valid_thu]
      ,[valid_fri]
      ,[valid_sat]
      ,[tpattern_id]
      ,[veh_disp_code]
      ,[build_time]
      ,[event_status]
      ,[note_2]
      ,[original_trip_no]
      ,[replace_trip_no]
      ,[is_cancelled]
      ,[blocking_gar_id]
      ,[rpattern_id]
      ,[sysrecno]
      ,[tbldp_no]
      ,[rv_id]
  FROM [hastus].[ltd_trip_converted_nulls]


INSERT hastus.temp_PosterViewOne (
[booking_id]
,[trip_no]
,[stop position in trip]
,[stop_id_1]
,[stop_no]
,[stop_description]
,[day]
,[vscver_id]
,[time]
,[route_destination]
,[drop_off_only]
,[route_id_1]
,[direction]
,[dir]
,[rte]
,[rte_and_dir]
,[rte_dir_destination]
,[rv_id]
,[tpattern_id]
,[trip_note_id]
,[stop position of last stop in trip]
,[place of last stop in trip]
,[stp_position of previous tp]
,[time_factor])
SELECT [booking_id]
      ,[trip_no]
      ,[stop position in trip]
      ,[stop_id_1]
      ,[stop_no]
      ,[stop_description]
      ,[day]
      ,[vscver_id]
      ,[time]
      ,[route_destination]
      ,[drop_off_only]
      ,[route_id_1]
      ,[direction]
      ,[dir]
      ,[rte]
      ,[rte_and_dir]
      ,[rte_dir_destination]
      ,[rv_id]
      ,[tpattern_id]
      ,[trip_note_id]
      ,[stop position of last stop in trip]
      ,[place of last stop in trip]
      ,[stp_position of previous tp]
      ,[time_factor]
  FROM [ltd_dw].[hastus].[ltd_poster_view_one]


INSERT hastus.temp_PosterViewTwo(
[stop_id_1]
,[stop position in trip]
,[stop position of last stop in trip]
,[stop_no]
,[stop_description]
,[trip_no]
,[day]
,[vscver_id]
,[time]
,[route_destination]
,[route_id_1]
,[dir]
,[rte]
,[rte_and_dir]
,[rte_dir_destination]
,[drop_off_only]
,[previous_tp_id]
,[previous_tp_description]
,[previous_tp_place_description]
,[place of last stop in trip]
,[booking_id]
,[trip_note_id])
SELECT [stop_id_1]
      ,[stop position in trip]
      ,[stop position of last stop in trip]
      ,[stop_no]
      ,[stop_description]
      ,[trip_no]
      ,[day]
      ,[vscver_id]
      ,[time]
      ,[route_destination]
      ,[route_id_1]
      ,[dir]
      ,[rte]
      ,[rte_and_dir]
      ,[rte_dir_destination]
      ,[drop_off_only]
      ,[previous_tp_id]
      ,[previous_tp_description]
      ,[previous_tp_place_description]
      ,[place of last stop in trip]
      ,[booking_id]
      ,[trip_note_id]
  FROM [hastus].[ltd_poster_view_two]

INSERT hastus.temp_PosterViewThree
([booking_id]
,[poster_seq_no]
,[poster_description]
,[trip_no]
,[stop_no]
,[stop_id_1]
,[stop_description]
,[stop_position_in_trip]
,[stop_position_of_last_stop_in_trip]
,[day]
,[vscver_id]
,[time]
,[route_destination]
,[rte]
,[dir]
,[rte_and_dir]
,[rte_dir_destination]
,[trip_footnote_id]
,[trip_footnote]
,[trip_footnote_2nd_piece]
,[drop_off_only]
,[previous_tp_id]
,[place of last stop in trip]
,[previous_tp_description]
,[previous_tp_place_description]
,[poster_format]
,[poster_route_id_1]
,[poster_footnote]
,[poster_footnote_length])
SELECT [booking_id]
      ,[poster_seq_no]
      ,[poster_description]
      ,[trip_no]
      ,[stop_no]
      ,[stop_id_1]
      ,[stop_description]
      ,[stop_position_in_trip]
      ,[stop_position_of_last_stop_in_trip]
      ,[day]
      ,[vscver_id]
      ,[time]
      ,[route_destination]
      ,[rte]
      ,[dir]
      ,[rte_and_dir]
      ,[rte_dir_destination]
      ,[trip_footnote_id]
      ,[trip_footnote]
      ,[trip_footnote_2nd_piece]
      ,[drop_off_only]
      ,[previous_tp_id]
      ,[place of last stop in trip]
      ,[previous_tp_description]
      ,[previous_tp_place_description]
      ,[poster_format]
      ,[poster_route_id_1]
      ,[poster_footnote]
      ,[poster_footnote_length]
  FROM [hastus].[ltd_poster_view_three]

INSERT hastus.temp_PosterViewThreeA
([booking_id]
      ,[poster_seq_no]
      ,[poster_description]
      ,[trip_no]
      ,[stop_no]
      ,[stop_id_1]
      ,[stop_description]
      ,[stop_position_in_trip]
      ,[stop_position_of_last_stop_in_trip]
      ,[day]
      ,[vscver_id]
      ,[rte]
      ,[dir]
      ,[rte_and_dir]
      ,[route_destination]
      ,[rte_dir_destination]
      ,[trip_footnote_id]
      ,[trip_footnote]
      ,[trip_footnote_2nd_piece]
      ,[drop_off_only]
      ,[previous_tp_id]
      ,[place of last stop in trip]
      ,[previous_tp_description]
      ,[previous_tp_place_description]
      ,[poster_format]
      ,[poster_route_id_1]
      ,[poster_footnote]
      ,[poster_footnote_length]
      ,[time])
SELECT [booking_id]
      ,[poster_seq_no]
      ,[poster_description]
      ,[trip_no]
      ,[stop_no]
      ,[stop_id_1]
      ,[stop_description]
      ,[stop_position_in_trip]
      ,[stop_position_of_last_stop_in_trip]
      ,[day]
      ,[vscver_id]
      ,[rte]
      ,[dir]
      ,[rte_and_dir]
      ,[route_destination]
      ,[rte_dir_destination]
      ,[trip_footnote_id]
      ,[trip_footnote]
      ,[trip_footnote_2nd_piece]
      ,[drop_off_only]
      ,[previous_tp_id]
      ,[place of last stop in trip]
      ,[previous_tp_description]
      ,[previous_tp_place_description]
      ,[poster_format]
      ,[poster_route_id_1]
      ,[poster_footnote]
      ,[poster_footnote_length]
      ,[time]
  FROM [hastus].[ltd_poster_view_three_a]

INSERT hastus.temp_PosterViewThreeB
([booking_id]
,[poster_seq_no]
,[poster_description]
,[trip_no]
,[stop_no]
,[stop_id_1]
,[stop_description]
,[stop_position_in_trip]
,[stop_position_of_last_stop_in_trip]
,[day]
,[vscver_id]
,[rte]
,[dir]
,[rte_and_dir]
,[route_destination]
,[rte_dir_destination]
,[trip_footnote_id]
,[trip_footnote]
,[trip_footnote_2nd_piece]
,[drop_off_only]
,[previous_tp_id]
,[place of last stop in trip]
,[previous_tp_description]
,[previous_tp_place_description]
,[poster_format]
,[poster_route_id_1]
,[poster_footnote]
,[poster_footnote_length]
,[time]
,[time_hour]
,[time_minute])
SELECT [booking_id]
      ,[poster_seq_no]
      ,[poster_description]
      ,[trip_no]
      ,[stop_no]
      ,[stop_id_1]
      ,[stop_description]
      ,[stop_position_in_trip]
      ,[stop_position_of_last_stop_in_trip]
      ,[day]
      ,[vscver_id]
      ,[rte]
      ,[dir]
      ,[rte_and_dir]
      ,[route_destination]
      ,[rte_dir_destination]
      ,[trip_footnote_id]
      ,[trip_footnote]
      ,[trip_footnote_2nd_piece]
      ,[drop_off_only]
      ,[previous_tp_id]
      ,[place of last stop in trip]
      ,[previous_tp_description]
      ,[previous_tp_place_description]
      ,[poster_format]
      ,[poster_route_id_1]
      ,[poster_footnote]
      ,[poster_footnote_length]
      ,[time]
      ,[time_hour]
      ,[time_minute]
  FROM [hastus].[ltd_poster_view_three_b]


INSERT hastus.temp_PosterViewFour (
[booking_id]
,[poster_seq_no]
,[poster_description]
,[poster_format_description]
,[poster_group]
,[trip_no]
,[stop_no]
,[stop_id_1]
,[stop_description]
,[stop_position_in_trip]
,[stop_position_of_last_stop_in_trip]
,[day]
,[rte]
,[dir]
,[rte_and_dir]
,[route_destination]
,[rte_dir_destination]
,[rte_emx]
,[trip_footnote_id]
,[trip_footnote]
,[trip_footnote_2nd_piece]
,[trip_footnote_char]
,[drop_off_only]
,[previous_tp_id]
,[place of last stop in trip]
,[previous_tp_description]
,[previous_tp_place_description]
,[poster_format]
,[poster_route_id_1]
,[poster_footnote]
,[poster_footnote_length]
,[time]
,[time_hour]
,[time_minute]
,[svc]
,[service]
,[svc_sort]
,[time_ampm]
,[time_disp]
,[time_col])
SELECT [booking_id]
      ,[poster_seq_no]
      ,[poster_description]
      ,[poster_format_description]
      ,[poster_group]
      ,[trip_no]
      ,[stop_no]
      ,[stop_id_1]
      ,[stop_description]
      ,[stop_position_in_trip]
      ,[stop_position_of_last_stop_in_trip]
      ,[day]
      ,[rte]
      ,[dir]
      ,[rte_and_dir]
      ,[route_destination]
      ,[rte_dir_destination]
      ,[rte_emx]
      ,[trip_footnote_id]
      ,[trip_footnote]
      ,[trip_footnote_2nd_piece]
      ,[trip_footnote_char]
      ,[drop_off_only]
      ,[previous_tp_id]
      ,[place of last stop in trip]
      ,[previous_tp_description]
      ,[previous_tp_place_description]
      ,[poster_format]
      ,[poster_route_id_1]
      ,[poster_footnote]
      ,[poster_footnote_length]
      ,[time]
      ,[time_hour]
      ,[time_minute]
      ,[svc]
      ,[service]
      ,[svc_sort]
      ,[time_ampm]
      ,[time_disp]
      ,[time_col]
  FROM [hastus].[ltd_poster_view_four]
GO
